import { Link } from "react-router-dom";
import { AlertTriangle, ArrowRight, ArrowRightLeft, BedDouble, CalendarCheck, ChefHat, CircleDollarSign, ClipboardCheck, DatabaseZap, LayoutDashboard, PackageSearch, Receipt, ShieldCheck, Users, Wallet, Tags } from "lucide-react";
import { Button } from "../../components/ui";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { StatusBadge } from "../../components/StatusBadge";
import { useAuth } from "../../context/AuthContext";
import { useFetch } from "../../hooks/useFetch";

const groups = [
  { title: "Atiende primero", description: "Recepción, pagos pendientes, incidencias y llegadas.", icon: BedDouble, tone: "blue", items: [["Recepción en vivo", "/recepcion"], ["Caja central", "/admin-panel/caja-central"], ["Incidencias", "/incidencias"], ["Reservas y eventos", "/reservas"]] },
  { title: "Ventas y experiencia", description: "Todo lo que el cliente ve, elige y paga.", icon: Tags, tone: "amber", items: [["Precios y tarifas", "/admin/comercial"], ["Carta y precios", "/inventario"], ["Eventos", "/eventos/calendario"], ["Habitaciones", "/habitaciones"]] },
  { title: "Inventario y producción", description: "Compras reales, recetas, stock, mermas y cierres.", icon: PackageSearch, tone: "green", items: [["Control de inventario", "/admin/inventario"], ["Recetas técnicas", "/inventario/recetas"], ["Compras", "/compras"], ["Cierres por turno", "/inventario/turnos"]] },
  { title: "Equipo y supervisión", description: "Personal, cocina, bar, limpieza y controles seguros.", icon: Users, tone: "violet", items: [["Cocina y Bar", "/admin/restaurante/resumen"], ["Limpieza", "/admin/limpieza/resumen"], ["Personal y turnos", "/empleados"], ["Control avanzado", "/admin/integridad"]] }
];

export function AdminCommandCenter() {
  const { user } = useAuth();
  const { data, loading, error, reload } = useFetch("/dashboard", { initialData: { metrics: {}, modules: { orders: [], cleaning: [] }, lowStockProducts: [] }, cacheTime: 15000, realtime: true });
  if (loading) return <LoadingSpinner/>;
  if (error) return <div className="rounded-card border border-red-200 bg-red-50 p-5 text-red-700">{error.message}</div>;
  const metrics = data.metrics || {}; const orders = data.modules?.orders || []; const cleaning = data.modules?.cleaning || []; const stock = data.lowStockProducts || [];
  const alerts = [
    { label: "Pedidos atrasados", value: metrics.delayedOrders || 0, href: "/admin/restaurante/resumen", urgent: metrics.delayedOrders > 0 },
    { label: "Pagos pendientes", value: metrics.pendingPayments || 0, href: "/pagos", urgent: metrics.pendingPayments > 0 },
    { label: "Incidencias abiertas", value: metrics.incidentsOpen || 0, href: "/incidencias", urgent: metrics.incidentsHighPriority > 0 },
    { label: "Stock crítico", value: stock.length, href: "/admin/inventario", urgent: stock.length > 0 }
  ];
  return <div className="space-y-5 pb-10">
    <section className="relative overflow-hidden rounded-card border border-park-border bg-white p-6 shadow-card"><div className="absolute -right-10 -top-16 text-blue-50"><LayoutDashboard size={240} strokeWidth={1}/></div><div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Centro de control del dueño</p><h1 className="mt-2 text-3xl font-black tracking-tight text-park-dark">Buenas tardes, {user?.firstName || "Administrador"}</h1><p className="mt-2 max-w-2xl text-sm text-park-muted">Primero atiende alertas y dinero. Después revisa ventas, inventario y equipo. Todas las tarifas que ve el cliente se cambian desde Precios y tarifas.</p></div><div className="flex flex-wrap gap-2"><Button as={Link} to="/admin/comercial" icon={Tags}>Precios y tarifas</Button><Button as={Link} to="/admin-panel/caja-central" variant="secondary" icon={Wallet}>Caja central</Button><Button onClick={reload} variant="gold">Actualizar</Button></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Ingresos hoy" value={money(metrics.incomeToday)} help={`Efectivo ${money(metrics.cashToday)}`} tone="blue" icon={CircleDollarSign}/><Metric label="Ocupación" value={metrics.occupiedRooms || 0} help={`${metrics.availableRooms || 0} habitaciones libres`} tone="green" icon={BedDouble}/><Metric label="Personal activo" value={metrics.activeStaff || 0} help="Con turno iniciado" tone="violet" icon={Users}/><Metric label="Pedidos activos" value={orders.length} help={`${metrics.delayedOrders || 0} fuera de tiempo`} tone="amber" icon={ChefHat}/><Metric label="Limpiezas" value={cleaning.length} help="Habitaciones por liberar" tone="cyan" icon={ClipboardCheck}/><Metric label="Cochera" value={metrics.parkingOccupied || 0} help="Espacios ocupados" tone="slate" icon={CalendarCheck}/></section>

    <section className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-black text-park-dark">Atención prioritaria</h2><p className="text-sm text-park-muted">El administrador interviene donde la operación necesita apoyo.</p></div><AlertTriangle className="text-amber-500"/></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{alerts.map((item)=><Link className={`flex items-center justify-between rounded-xl border p-4 ${item.urgent ? "border-amber-200 bg-amber-50" : "border-park-border bg-park-bg"}`} to={item.href} key={item.label}><div><strong className="block text-2xl text-park-dark">{item.value}</strong><span className="text-sm font-bold text-park-muted">{item.label}</span></div><ArrowRight size={18} className={item.urgent ? "text-amber-600" : "text-park-muted"}/></Link>)}</div></section>

    <section><div className="mb-3"><h2 className="text-xl font-black text-park-dark">Todos los sistemas, una sola operación</h2><p className="text-sm text-park-muted">Cada área conserva su independencia; Administración puede supervisar y entrar a cualquiera.</p></div><div className="grid gap-4 xl:grid-cols-2">{groups.map((group)=><ModuleGroup group={group} key={group.title}/>)}</div></section>

    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-park-dark">Operación en vivo</h2><p className="text-sm text-park-muted">Pedidos que requieren seguimiento.</p></div><Link className="text-xs font-black text-blue-600" to="/admin/restaurante/resumen">Ver monitores</Link></div>{orders.length ? <div className="space-y-2">{orders.slice(0,6).map((order)=><div className="flex items-center justify-between gap-3 rounded-xl border border-park-border bg-park-bg p-3" key={order.id}><div><strong className="text-sm text-park-dark">{order.code} · {order.area}</strong><p className="text-xs text-park-muted">{order.destination?.label || "Destino por confirmar"} · {order.elapsedMinutes || 0} min</p></div><StatusBadge value={order.operationalBucketLabel || order.status}/></div>)}</div> : <p className="rounded-xl bg-park-bg p-5 text-center text-sm text-park-muted">No hay pedidos activos.</p>}</article><article className="rounded-card border border-park-border bg-white p-5 shadow-card"><h2 className="font-black text-park-dark">Controles del dueño</h2><p className="mb-4 text-sm text-park-muted">Revisa estos puntos antes del cierre diario.</p><OwnerLink icon={Receipt} label="Cuadre y pagos" href="/admin-panel/caja-central"/><OwnerLink icon={ArrowRightLeft} label="Inventarios por turno" href="/inventario/turnos"/><OwnerLink icon={DatabaseZap} label="Integridad de datos" href="/admin/integridad"/><OwnerLink icon={ShieldCheck} label="Usuarios y permisos" href="/roles"/></article></section>
  </div>;
}

function ModuleGroup({ group }) { const Icon=group.icon; const tones={blue:"bg-blue-50 text-blue-700",amber:"bg-amber-50 text-amber-700",green:"bg-emerald-50 text-emerald-700",violet:"bg-violet-50 text-violet-700"}; return <article className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${tones[group.tone]}`}><Icon size={22}/></span><div><h3 className="font-black text-park-dark">{group.title}</h3><p className="text-sm text-park-muted">{group.description}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{group.items.map(([label,href])=><Link className="flex items-center justify-between rounded-xl border border-park-border bg-park-bg px-4 py-3 text-sm font-black text-park-dark hover:border-blue-300 hover:bg-blue-50" to={href} key={href}>{label}<ArrowRight size={16}/></Link>)}</div></article>; }
function Metric({ label, value, help, tone, icon: Icon }) { const colors={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",violet:"bg-violet-50 text-violet-700",amber:"bg-amber-50 text-amber-700",cyan:"bg-cyan-50 text-cyan-700",slate:"bg-slate-100 text-slate-700"}; return <article className="rounded-card border border-park-border bg-white p-4 shadow-card"><span className={`grid h-9 w-9 place-items-center rounded-lg ${colors[tone]}`}><Icon size={18}/></span><strong className="mt-3 block text-2xl text-park-dark">{value}</strong><p className="text-sm font-black text-park-dark">{label}</p><small className="text-park-muted">{help}</small></article>; }
function OwnerLink({ icon: Icon, label, href }) { return <Link className="mt-2 flex items-center gap-3 rounded-xl border border-park-border p-3 text-sm font-black text-park-dark hover:bg-park-bg" to={href}><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon size={17}/></span>{label}<ArrowRight className="ml-auto text-park-muted" size={16}/></Link>; }
function money(value) { return `S/ ${Number(value || 0).toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
