import { Link } from "react-router-dom";
import { AlertTriangle, ArrowRight, ArrowRightLeft, BedDouble, CalendarCheck, CalendarClock, Camera, ChefHat, CircleDollarSign, ClipboardCheck, DatabaseZap, LayoutDashboard, PackageSearch, Receipt, ShieldCheck, Users, Wallet, Tags, Car, Waves, ShoppingCart, FileText, Wrench, Factory, Boxes, LockKeyhole, ContactRound, DollarSign, UserCog, KeyRound, BarChart3, Sparkles } from "lucide-react";
import { Button } from "../../components/ui";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { StatusBadge } from "../../components/StatusBadge";
import { useAuth } from "../../context/AuthContext";
import { useFetch } from "../../hooks/useFetch";

const superAdminGroups = [
  { title: "Estadía y huéspedes", description: "El ciclo de reserva, habitación, llegada, salida, cliente y pago en una sola vista de control.", icon: BedDouble, tone: "blue", items: [["Habitaciones", "/habitaciones"], ["Reservas", "/reservas"], ["Check-in y check-out", "/checkin"], ["Clientes", "/clientes"], ["Pagos y cuentas", "/pagos"]] },
  { title: "Servicios y experiencia del cliente", description: "Piscina, mirador, eventos y cochera: el pago y la validación habilitan el servicio correspondiente, sin QR por mesa.", icon: Waves, tone: "amber", items: [["Accesos de servicios", "/accesos"], ["Piscina y mirador", "/piscina/ingresos"], ["Eventos", "/eventos/reservas"], ["Calendario de eventos", "/eventos/calendario"], ["Contratos de eventos", "/eventos/contratos"], ["Cochera", "/cochera"]] },
  { title: "Operación y soporte", description: "Recepción, limpieza, evidencias, mantenimiento e incidencias quedan visibles para el dueño.", icon: Sparkles, tone: "blue", items: [["Recepción en vivo", "/recepcion"], ["Supervisión de limpieza", "/admin/limpieza/resumen"], ["Evidencias de limpieza", "/admin/limpieza/evidencias"], ["Mantenimiento e incidencias", "/incidencias"]] },
  { title: "Restaurante y bar", description: "Los pedidos pagados por clientes autorizados llegan a cada estación; el Superadmin ve sus estados, carta y recetas.", icon: ChefHat, tone: "green", items: [["Monitor · Restaurante", "/control-gastronomico/restaurante"], ["Monitor · Bar", "/control-gastronomico/bar"], ["Carta, platos y tragos", "/admin/alimentos-bebidas"], ["Recetas técnicas", "/inventario/recetas"]] },
  { title: "Inventario y abastecimiento", description: "Stock central, compras, proveedores, producción, porcionado y cierres de inventario.", icon: Boxes, tone: "green", items: [["Inventario central", "/admin/inventario"], ["Compras", "/compras"], ["Proveedores", "/proveedores"], ["Producción y porcionado", "/inventario/produccion"], ["Cierres de inventario", "/inventario/turnos"]] },
  { title: "Personal y finanzas", description: "Personal, programación de turnos, planilla, caja y reportes; sin biometría en esta versión.", icon: Users, tone: "violet", items: [["Personal", "/empleados"], ["Turnos y planilla", "/turnos"], ["Caja central", "/admin-panel/caja-central"], ["Reportes", "/reportes"]] },
  { title: "Gobierno y seguridad", description: "Usuarios, permisos, auditoría, integridad y configuración general del hotel.", icon: ShieldCheck, tone: "violet", items: [["Usuarios y permisos", "/usuarios"], ["Roles y permisos", "/roles"], ["Auditoría y seguridad", "/auditoria"], ["Integridad de datos", "/admin/integridad"], ["Configuración", "/configuracion"]] }
];

const adminGroups = [
  { title: "1. Atención y cobros", description: "Eres responsable de atender al huésped, registrar sus movimientos y rendir el efectivo de tu turno al Superadmin.", icon: BedDouble, tone: "blue", items: [["Recepción en vivo", "/recepcion"], ["Reservas", "/reservas"], ["Llegadas y salidas", "/checkin"], ["Mi caja y cierre", "/admin-panel/mi-caja"]] },
  { title: "2. Servicios y accesos", description: "Confirma pago, revisa el QR y habilita exactamente el servicio que el cliente compró: hospedaje, piscina, mirador o evento.", icon: Waves, tone: "amber", items: [["Validar QR y accesos", "/accesos"], ["Hospedaje", "/habitaciones"], ["Piscina y mirador", "/piscina/ingresos"], ["Eventos y cochera", "/eventos/reservas"]] },
  { title: "3. Coordinación hotelera", description: "No reemplazas a Restaurante o Bar: supervisas sus pedidos. También coordinas por WhatsApp las evidencias y el soporte de habitaciones.", icon: ChefHat, tone: "green", items: [["Monitor de restaurante", "/control-gastronomico/restaurante"], ["Monitor de bar", "/control-gastronomico/bar"], ["Habitaciones y evidencias", "/admin/limpieza/resumen"], ["Incidencias y mantenimiento", "/incidencias"]] },
  { title: "4. Personal de turno", description: "Consulta qué personal está programado y quién está activo. El Superadmin conserva las decisiones de precio, permisos y aprobaciones finales.", icon: Users, tone: "violet", items: [["Personal activo", "/empleados"], ["Turnos programados", "/turnos"], ["Reportar al Superadmin", "/reportes"]] }
];

export function AdminCommandCenter() {
  const { user } = useAuth();
  const { data, loading, error, reload } = useFetch("/dashboard", { initialData: { metrics: {}, modules: { orders: [], cleaning: [] }, lowStockProducts: [] }, cacheTime: 15000, realtime: true });
  if (loading) return <LoadingSpinner/>;
  if (error) return <div className="rounded-card border border-red-200 bg-red-50 p-5 text-red-700">{error.message}</div>;
  const metrics = data.metrics || {}; const orders = data.modules?.orders || []; const cleaning = data.modules?.cleaning || []; const stock = data.lowStockProducts || [];
  const alerts = [
    { label: "Pedidos atrasados", value: metrics.delayedOrders || 0, href: "/control-gastronomico/restaurante", urgent: metrics.delayedOrders > 0 },
    { label: "Pagos pendientes", value: metrics.pendingPayments || 0, href: "/pagos", urgent: metrics.pendingPayments > 0 },
    { label: "Incidencias abiertas", value: metrics.incidentsOpen || 0, href: "/incidencias", urgent: metrics.incidentsHighPriority > 0 },
    { label: "Stock crítico", value: stock.length, href: "/admin/inventario", urgent: stock.length > 0 }
  ];
  return <div className="reception-command space-y-6 pb-10">
    <section className="reception-status"><strong>Conectado al ERP</strong><span>clientes, reservas, pagos, accesos, pedidos y evidencias se actualizan automáticamente.</span></section>
    <section className="reception-hero"><div><p>ADMIN RECEPCIÓN · CONTROL OPERATIVO</p><h1>Centro de operaciones</h1><span>Lectura transversal de huéspedes, servicios, cobros y coordinación interna durante tu turno.</span></div><div className="flex flex-wrap gap-2"><Button as={Link} to="/recepcion" icon={ClipboardCheck}>Atender recepción</Button><Button as={Link} to="/reservas?nueva=1" variant="gold">Nueva reserva</Button></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Disponibles" value={metrics.availableRooms || 0} help="Habitaciones libres" tone="green" icon={BedDouble}/><Metric label="Ocupadas" value={metrics.occupiedRooms || 0} help="Ocupación actual" tone="violet" icon={BedDouble}/><Metric label="Llegadas" value={metrics.arrivalsToday || 0} help="Reservas confirmadas" tone="blue" icon={CalendarCheck}/><Metric label="Ingresos registrados" value={money(metrics.incomeToday)} help={`Efectivo ${money(metrics.cashToday)}`} tone="amber" icon={CircleDollarSign}/><Metric label="Pedidos" value={orders.length} help={`${metrics.delayedOrders || 0} fuera de tiempo`} tone="cyan" icon={ChefHat}/><Metric label="Alertas" value={(metrics.incidentsOpen || 0) + cleaning.length} help="Soporte y evidencias" tone="slate" icon={AlertTriangle}/></section>

    <section className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-black text-park-dark">Atención prioritaria</h2><p className="text-sm text-park-muted">El administrador interviene donde la operación necesita apoyo.</p></div><AlertTriangle className="text-amber-500"/></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{alerts.map((item)=><Link className={`flex items-center justify-between rounded-xl border p-4 ${item.urgent ? "border-amber-200 bg-amber-50" : "border-park-border bg-park-bg"}`} to={item.href} key={item.label}><div><strong className="block text-2xl text-park-dark">{item.value}</strong><span className="text-sm font-bold text-park-muted">{item.label}</span></div><ArrowRight size={18} className={item.urgent ? "text-amber-600" : "text-park-muted"}/></Link>)}</div></section>

    <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Módulos de responsabilidad</p><h2 className="text-xl font-black text-park-dark">Tu estación de control</h2><p className="text-sm text-park-muted">Cada módulo agrupa sus vistas internas. Restaurante y Bar conservan su propia operación; tú coordinas, verificas y dejas trazabilidad.</p></div><div className="grid gap-4 xl:grid-cols-2">{adminGroups.map((group)=><ModuleGroup group={group} key={group.title}/>)}</div></section>

      <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-park-dark">Operación en vivo</h2><p className="text-sm text-park-muted">Pedidos que requieren coordinación desde recepción.</p></div><Link className="text-xs font-black text-blue-600" to="/control-gastronomico/restaurante">Ver monitores</Link></div>{orders.length ? <div className="space-y-2">{orders.slice(0,6).map((order)=><div className="flex items-center justify-between gap-3 rounded-xl border border-park-border bg-park-bg p-3" key={order.id}><div><strong className="text-sm text-park-dark">{order.code} · {order.area}</strong><p className="text-xs text-park-muted">{order.destination?.label || "Destino por confirmar"} · {order.elapsedMinutes || 0} min</p></div><StatusBadge value={order.operationalBucketLabel || order.status}/></div>)}</div> : <p className="rounded-xl bg-park-bg p-5 text-center text-sm text-park-muted">No hay pedidos activos.</p>}</article><article className="rounded-card border border-park-border bg-white p-5 shadow-card"><h2 className="font-black text-park-dark">Control de recepción</h2><p className="mb-4 text-sm text-park-muted">Puntos que debe vigilar durante su jornada.</p><OwnerLink icon={Receipt} label="Cuadre y pagos" href="/admin-panel/mi-caja"/><OwnerLink icon={ShieldCheck} label="Accesos de servicios" href="/accesos"/><OwnerLink icon={Wrench} label="Solicitudes e incidencias" href="/incidencias"/><OwnerLink icon={ClipboardCheck} label="Habitaciones y evidencias WhatsApp" href="/admin/limpieza/resumen"/></article></section>
  </div>;
}

function ModuleGroup({ group }) { const Icon=group.icon; const tones={blue:"bg-blue-50 text-blue-700",amber:"bg-amber-50 text-amber-700",green:"bg-emerald-50 text-emerald-700",violet:"bg-violet-50 text-violet-700"}; return <article className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${tones[group.tone]}`}><Icon size={22}/></span><div><h3 className="font-black text-park-dark">{group.title}</h3><p className="text-sm text-park-muted">{group.description}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{group.items.map(([label,href])=><Link className="flex items-center justify-between rounded-xl border border-park-border bg-park-bg px-4 py-3 text-sm font-black text-park-dark hover:border-blue-300 hover:bg-blue-50" to={href} key={href}>{label}<ArrowRight size={16}/></Link>)}</div></article>; }
function Metric({ label, value, help, tone, icon: Icon }) { const colors={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",violet:"bg-violet-50 text-violet-700",amber:"bg-amber-50 text-amber-700",cyan:"bg-cyan-50 text-cyan-700",slate:"bg-slate-100 text-slate-700"}; return <article className="rounded-card border border-park-border bg-white p-4 shadow-card"><span className={`grid h-9 w-9 place-items-center rounded-lg ${colors[tone]}`}><Icon size={18}/></span><strong className="mt-3 block text-2xl text-park-dark">{value}</strong><p className="text-sm font-black text-park-dark">{label}</p><small className="text-park-muted">{help}</small></article>; }
function OwnerLink({ icon: Icon, label, href }) { return <Link className="mt-2 flex items-center gap-3 rounded-xl border border-park-border p-3 text-sm font-black text-park-dark hover:bg-park-bg" to={href}><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon size={17}/></span>{label}<ArrowRight className="ml-auto text-park-muted" size={16}/></Link>; }
function money(value) { return `S/ ${Number(value || 0).toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
