import { useEffect, useMemo, useState } from "react";
import { BedDouble, Image, Save, Search, Trash2, Upload } from "lucide-react";
import { Alert, Button, Input, PageHeader } from "../../components/ui";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { Toast } from "../../components/Toast";
import { useFetch } from "../../hooks/useFetch";
import { api, getToken } from "../../services/api";
import { apiBaseUrl } from "../../config/api";

const labels = { HOSPEDAJE: "Hospedaje", PISCINA: "Piscina", MIRADOR: "Mirador", EVENTOS: "Eventos", BAR: "Bar", TERRAZA: "Terraza" };
const placeholderImage = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='480' height='320'%3E%3Crect width='100%25' height='100%25' fill='%23edf2ef'/%3E%3Cpath d='M180 205l45-48 30 30 35-42 55 60H180z' fill='%23b9cabf'/%3E%3Ccircle cx='185' cy='120' r='22' fill='%23d0aa4d'/%3E%3C/svg%3E";
const imageFallback = (event) => { event.currentTarget.onerror = null; event.currentTarget.src = placeholderImage; };

async function uploadImage(path, file) {
  if (!file) return null;
  const response = await fetch(`${apiBaseUrl}${path}`, { method: "POST", headers: { Authorization: `Bearer ${getToken()}`, "Content-Type": file.type }, body: file });
  const data = await response.json().catch(() => null);
  if (!response.ok) throw new Error(data?.message || "No se pudo subir la imagen");
  return data;
}

export function CatalogContentPage() {
  const commercial = useFetch("/admin/commercial-settings", { initialData: null, cacheTime: 0 });
  const menu = useFetch("/admin/menu-items", { initialData: [], pollInterval: 30000 });
  const [media, setMedia] = useState([]); const [roomTypes, setRoomTypes] = useState([]); const [serviceCode, setServiceCode] = useState("HOSPEDAJE"); const [roomName, setRoomName] = useState(""); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(""); const [area, setArea] = useState("TODOS"); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [failure, setFailure] = useState("");
  useEffect(() => { if (commercial.data?.experienceMedia) setMedia(structuredClone(commercial.data.experienceMedia)); if (commercial.data?.roomTypes) { setRoomTypes(structuredClone(commercial.data.roomTypes)); setRoomName((current) => current || commercial.data.roomTypes[0]?.name || ""); } }, [commercial.data]);
  const products = useMemo(() => (menu.data || []).filter((item) => (area === "TODOS" || item.area === area) && `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [menu.data, area, query]);
  const currentMedia = media.find((item) => item.code === serviceCode) || media[0];
  const currentRoom = roomTypes.find((item) => item.name === roomName) || roomTypes[0];
  if (commercial.loading || menu.loading || !commercial.data) return <LoadingSpinner label="Cargando contenido del cliente..." />;
  if (commercial.error || menu.error) return <Alert tone="danger" title="No se pudo cargar el contenido">{commercial.error?.message || menu.error?.message}</Alert>;
  const updateMedia = (key, value) => setMedia((current) => current.map((item) => item.code === serviceCode ? { ...item, [key]: value } : item));
  const updateRoom = (key, value) => setRoomTypes((current) => current.map((item) => item.name === roomName ? { ...item, [key]: value } : item));
  async function savePresentation() { setSaving(true); setFailure(""); try { await api("/admin/commercial-settings", { method: "PUT", body: { experienceMedia: media, roomTypes } }); await commercial.reload(); setNotice("Los textos e imágenes de la experiencia del cliente fueron guardados."); } catch (error) { setFailure(error.message); } finally { setSaving(false); } }
  async function changeImage(path, file, message) { setSaving(true); setFailure(""); try { await uploadImage(path, file); await commercial.reload(); await menu.reload(); setNotice(message); } catch (error) { setFailure(error.message); } finally { setSaving(false); } }
  async function removeImage(path, message) { setSaving(true); setFailure(""); try { await api(path, { method: "DELETE" }); await commercial.reload(); await menu.reload(); setNotice(message); } catch (error) { setFailure(error.message); } finally { setSaving(false); } }
  async function saveProduct(event) { event.preventDefault(); if (!selected) return; setSaving(true); setFailure(""); try { await api(`/admin/menu-items/${selected.id}`, { method: "PUT", body: selected }); await menu.reload(); setSelected(null); setNotice("La información visible del producto fue actualizada."); } catch (error) { setFailure(error.message); } finally { setSaving(false); } }
  return <main className="catalog-modern space-y-6 pb-10"><Toast message={notice} onClose={() => setNotice("")} /><PageHeader eyebrow="Catálogo · experiencia del cliente" title="Contenido e imágenes" description="Aquí controlas lo que ve el cliente: portadas, habitaciones, platos y bebidas." actions={<Button icon={Save} loading={saving} onClick={savePresentation}>Guardar textos</Button>}/>{failure ? <Alert tone="danger" title="No se pudo guardar">{failure}</Alert> : null}
    <section className="catalog-modern__guide"><Image size={22}/><div><strong>Todo el contenido en un solo lugar</strong><span>Sube JPG, PNG o WEBP desde tu laptop. Reemplazar o quitar una foto no cambia precios, inventario ni reservas.</span></div></section>
    <section className="catalog-modern__content-manager"><div className="catalog-modern__heading"><p>PORTADAS</p><h2>Mensaje principal de cada servicio</h2><span>Elige un servicio. Solo se abre una ficha a la vez.</span></div><div className="catalog-modern__content-tabs">{media.map((item) => <button className={serviceCode === item.code ? "is-active" : ""} key={item.code} onClick={() => setServiceCode(item.code)} type="button">{labels[item.code] || item.code}</button>)}</div>{currentMedia ? <div className="catalog-modern__content-editor"><div className="catalog-modern__image-control"><img onError={imageFallback} src={currentMedia.imageUrl || placeholderImage} alt={labels[currentMedia.code] || currentMedia.code}/><label className="catalog-modern__upload"><Upload size={16}/>Subir o reemplazar<input accept="image/jpeg,image/png,image/webp" onChange={(event) => changeImage(`/admin/experience-media/${currentMedia.code}/image`, event.target.files?.[0], `La portada de ${labels[currentMedia.code]} fue guardada.`)} type="file"/></label>{currentMedia.imageUrl ? <button className="catalog-modern__remove" onClick={() => removeImage(`/admin/experience-media/${currentMedia.code}/image`, "La imagen fue quitada. Puedes subir una nueva cuando quieras.")} type="button"><Trash2 size={15}/>Quitar foto</button> : null}</div><div className="catalog-modern__content-fields"><p>{labels[currentMedia.code]}</p><Input label="Título" value={currentMedia.title || ""} onChange={(event) => updateMedia("title", event.target.value)}/><Input label="Subtítulo" value={currentMedia.title2 || ""} onChange={(event) => updateMedia("title2", event.target.value)}/><Input label="Descripción" value={currentMedia.description || ""} onChange={(event) => updateMedia("description", event.target.value)}/></div></div> : null}</section>
    <section className="catalog-modern__content-manager"><div className="catalog-modern__heading"><p>HABITACIONES</p><h2>Foto del interior y descripción</h2><span>El cliente verá esta imagen al abrir el detalle de una habitación.</span></div><div className="catalog-modern__content-tabs">{roomTypes.map((room) => <button className={roomName === room.name ? "is-active" : ""} key={room.name} onClick={() => setRoomName(room.name)} type="button">{room.name}</button>)}</div>{currentRoom ? <div className="catalog-modern__content-editor"><div className="catalog-modern__image-control"><img onError={imageFallback} src={currentRoom.imageUrl || placeholderImage} alt={currentRoom.name}/><label className="catalog-modern__upload"><Upload size={16}/>Subir interior<input accept="image/jpeg,image/png,image/webp" onChange={(event) => changeImage(`/admin/room-types/${encodeURIComponent(currentRoom.name)}/image`, event.target.files?.[0], `La foto de ${currentRoom.name} fue guardada.`)} type="file"/></label>{currentRoom.imageUrl ? <button className="catalog-modern__remove" onClick={() => removeImage(`/admin/room-types/${encodeURIComponent(currentRoom.name)}/image`, "La foto de habitación fue quitada.")} type="button"><Trash2 size={15}/>Quitar foto</button> : null}</div><div className="catalog-modern__content-fields"><p><BedDouble size={15}/>{currentRoom.name} · hasta {currentRoom.capacity} persona(s)</p><Input label="Descripción que verá el cliente" value={currentRoom.description || ""} onChange={(event) => updateRoom("description", event.target.value)}/><small>Guarda los textos con el botón superior.</small></div></div> : null}</section>
    <section><div className="catalog-modern__heading"><p>CARTA</p><h2>Fotos y descripciones de platos y bebidas</h2><span>Busca un producto y edita solo esa ficha.</span></div><div className="catalog-modern__filters"><label><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar plato o bebida"/></label>{[["TODOS", "Todos"], ["RESTAURANTE", "Restaurante"], ["BARTENDER", "Bar"]].map(([value, label]) => <button className={area === value ? "is-active" : ""} key={value} onClick={() => setArea(value)} type="button">{label}</button>)}</div><div className="catalog-modern__media-products">{products.map((item) => <button type="button" onClick={() => setSelected({ ...item })} key={item.id}><img src={item.image || ""} alt=""/><span><strong>{item.name}</strong><small>{item.area === "BARTENDER" ? "Bar" : "Restaurante"} · {item.category}</small></span><span>Editar</span></button>)}</div></section>
    {selected ? <div className="catalog-modern__drawer-backdrop" onMouseDown={() => setSelected(null)}><form className="catalog-modern__drawer" onMouseDown={(event) => event.stopPropagation()} onSubmit={saveProduct}><div><p>CONTENIDO DE CARTA</p><h2>{selected.name}</h2><span>Esta es la información visible para el cliente.</span></div><div className="catalog-modern__drawer-image"><img src={selected.image || ""} alt={selected.name}/><label className="catalog-modern__upload"><Upload size={16}/>Subir o reemplazar<input accept="image/jpeg,image/png,image/webp" onChange={(event) => changeImage(`/admin/menu-items/${selected.id}/image`, event.target.files?.[0], `La foto de ${selected.name} fue guardada.`)} type="file"/></label>{selected.image ? <button className="catalog-modern__remove" onClick={() => removeImage(`/admin/menu-items/${selected.id}/image`, "La foto del producto fue quitada.")} type="button"><Trash2 size={15}/>Quitar foto</button> : null}</div><Input label="Nombre visible" value={selected.name} onChange={(event) => setSelected({ ...selected, name: event.target.value })}/><Input label="Descripción" value={selected.description || ""} onChange={(event) => setSelected({ ...selected, description: event.target.value })}/><div className="catalog-modern__drawer-actions"><Button type="button" variant="secondary" onClick={() => setSelected(null)}>Cancelar</Button><Button type="submit" loading={saving} icon={Save}>Guardar texto</Button></div></form></div> : null}
  </main>;
}
