import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { BedDouble, Car, ChefHat, CircleDollarSign, Save, Sparkles, UtensilsCrossed, Waves } from "lucide-react";
import { Alert, Button, Input, PageHeader } from "../../components/ui";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { Toast } from "../../components/Toast";
import { useFetch } from "../../hooks/useFetch";
import { api } from "../../services/api";

const serviceIcon = { HOSPEDAJE: BedDouble, PISCINA: Waves, MIRADOR: Sparkles, EVENTOS: Sparkles };
const money = (value) => `S/ ${Number(value || 0).toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function CommercialSettingsPage() {
  const { data, loading, error, reload } = useFetch("/admin/commercial-settings", { initialData: null, cacheTime: 0 });
  const [form, setForm] = useState(null); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [failure, setFailure] = useState("");
  useEffect(() => { if (data) setForm(structuredClone(data)); }, [data]);
  if (loading || !form) return <LoadingSpinner label="Cargando tarifas..." />;
  if (error) return <Alert tone="danger" title="No se pudieron cargar las tarifas">{error.message}</Alert>;
  const change = (section, index, key, value) => setForm((current) => ({ ...current, [section]: current[section].map((item, row) => row === index ? { ...item, [key]: value } : item) }));
  const changePricing = (group, index, value) => setForm((current) => ({ ...current, experiencePricing: { ...current.experiencePricing, [group]: current.experiencePricing[group].map((item, row) => row === index ? { ...item, price: value } : item) } }));
  const changeMedia = (index, key, value) => setForm((current) => ({ ...current, experienceMedia: (current.experienceMedia || []).map((item, row) => row === index ? { ...item, [key]: value } : item) }));
  async function save(event) { event.preventDefault(); setSaving(true); setFailure(""); try { await api("/admin/commercial-settings", { method: "PUT", body: form }); setNotice("Tarifas actualizadas. Los nuevos clientes verán estos precios de inmediato."); await reload(); } catch (err) { setFailure(err.message); } finally { setSaving(false); } }
  return <form className="space-y-5 pb-10" onSubmit={save}>
    <Toast message={notice} onClose={() => setNotice("")} />
    <PageHeader eyebrow="Administrador · prioridad alta" title="Precios y tarifas de venta" description="Este es el único lugar para cambiar lo que ve y paga el cliente. Los cambios aplican a nuevas reservas, experiencias y pedidos; nunca alteran comprobantes ya pagados." actions={<Button type="submit" loading={saving} icon={Save}>Guardar todas las tarifas</Button>} />
    {failure ? <Alert tone="danger" title="No se pudo guardar">{failure}</Alert> : null}
    <section className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-xl bg-black text-white"><CircleDollarSign size={21}/></span><div><h2 className="font-black text-park-dark">Regla de precios</h2><p className="text-sm text-park-muted">Edita aquí las experiencias, habitaciones, cocheras y ambientes. Para platos y bebidas usa “Carta, precios y recetas” porque allí también se controla la porción y el costo.</p></div></div></section>
    <section><h2 className="mb-3 text-xl font-black text-park-dark">Experiencias para el cliente</h2><div className="grid gap-4 md:grid-cols-2">{form.services.map((service, index) => { const Icon = serviceIcon[service.code] || Sparkles; return <article className="rounded-card border border-park-border bg-white p-5 shadow-card" key={service.code}><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-park-bg text-park-dark"><Icon size={20}/></span><div><h3 className="font-black text-park-dark">{service.code === "HOSPEDAJE" ? "Hospedaje · tarifa de referencia" : service.name}</h3><p className="text-xs text-park-muted">{service.code === "HOSPEDAJE" ? "El precio final depende del tipo de habitación de abajo." : "Precio base por persona o experiencia."}</p></div></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Nombre visible" value={service.name} onChange={(e) => change("services", index, "name", e.target.value)} /><Input label="Precio base (S/)" type="number" min="0" step="0.01" value={service.price} onChange={(e) => change("services", index, "price", e.target.value)} />{service.capacity ? <Input label="Capacidad por horario" type="number" min="1" value={service.capacity} onChange={(e) => change("services", index, "capacity", e.target.value)} /> : null}</div></article>; })}</div></section>
    <section><div className="mb-3"><h2 className="text-xl font-black text-park-dark">Imágenes y textos publicados</h2><p className="text-sm text-park-muted">Aquí el Superadmin reemplaza las imágenes de demostración por enlaces a fotos reales. Al guardar, el portal de clientes consume estos datos desde el ERP.</p></div><div className="grid gap-4 xl:grid-cols-2">{(form.experienceMedia || []).map((media, index) => <article className="overflow-hidden rounded-card border border-park-border bg-white shadow-card" key={media.code}><div className="grid md:grid-cols-[11rem_1fr]"><img className="h-40 w-full bg-park-bg object-cover md:h-full" src={media.imageUrl || ""} alt={`Vista previa de ${media.place || media.code}`} /><div className="space-y-3 p-5"><div><p className="text-xs font-black uppercase tracking-[.14em] text-park-muted">{media.code}</p><h3 className="font-black text-park-dark">{media.place || "Servicio Park Plaza"}</h3></div><Input label="Lugar o subtítulo" value={media.place || ""} onChange={(e) => changeMedia(index, "place", e.target.value)} /><div className="grid gap-3 sm:grid-cols-2"><Input label="Título principal" value={media.title || ""} onChange={(e) => changeMedia(index, "title", e.target.value)} /><Input label="Título secundario" value={media.title2 || ""} onChange={(e) => changeMedia(index, "title2", e.target.value)} /></div><Input label="URL de imagen real" type="url" value={media.imageUrl || ""} onChange={(e) => changeMedia(index, "imageUrl", e.target.value)} /><Input label="Descripción" value={media.description || ""} onChange={(e) => changeMedia(index, "description", e.target.value)} /></div></div></article>)}</div></section>
    <section><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-xl font-black text-park-dark">Habitaciones</h2><p className="text-sm text-park-muted">Un cambio ajusta todas las habitaciones de ese tipo.</p></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{form.roomTypes.map((room, index) => <article className="rounded-card border border-park-border bg-white p-4 shadow-card" key={room.name}><BedDouble className="mb-3 text-park-dark" size={20}/><h3 className="font-black text-park-dark">{room.name}</h3><p className="mb-3 text-xs text-park-muted">{room.rooms} habitaciones · hasta {room.capacity} huésped(es)</p><Input label="Precio por noche (S/)" type="number" min="0" step="0.01" value={room.price} onChange={(e) => change("roomTypes", index, "price", e.target.value)} /></article>)}</div></section>
    <section className="grid gap-4 xl:grid-cols-2"><article className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-park-bg text-park-dark"><Car size={20}/></span><div><h2 className="font-black text-park-dark">Cochera</h2><p className="text-sm text-park-muted">La moto puede mantenerse gratuita. Autos y vehículos mayores se cobran por espacio.</p></div></div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(form.parkingRates || {}).map(([type, price]) => <Input key={type} label={`${type[0]}${type.slice(1).toLowerCase()} · S/`} type="number" min="0" step="0.01" value={price} onChange={(e) => setForm((current) => ({ ...current, parkingRates: { ...current.parkingRates, [type]: e.target.value } }))} />)}</div></article>
      <article className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-park-bg text-park-dark"><UtensilsCrossed size={20}/></span><div><h2 className="font-black text-park-dark">Carta, precios y recetas</h2><p className="text-sm text-park-muted">Aquí se cambian los precios de platos y bebidas, su disponibilidad, receta, gramajes, ml, rendimiento y costo.</p></div></div><Link className="inline-flex items-center rounded-button bg-black px-4 py-2.5 text-sm font-black text-white" to="/inventario">Administrar carta y recetas</Link><p className="mt-3 text-xs text-park-muted">Ejemplo: Lomo saltado tiene precio de venta, porción de lomo en gramos y sus insumos por plato.</p></article></section>
    <section><h2 className="mb-1 text-xl font-black text-park-dark">Planes, extras y producción</h2><p className="mb-3 text-sm text-park-muted">Tarifas adicionales que aparecen durante la experiencia del cliente.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Object.entries(form.experiencePricing || {}).map(([group, items]) => <article className="rounded-card border border-park-border bg-white p-4 shadow-card" key={group}><h3 className="mb-3 text-sm font-black text-park-dark">{group.replaceAll("_", " ")}</h3><div className="space-y-3">{items.map((item, index) => <div className="grid grid-cols-[1fr_7rem] items-end gap-2" key={item.code || item.id}><p className="pb-2 text-sm font-bold text-park-dark">{item.name}</p><Input aria-label={`Precio ${item.name}`} type="number" min="0" step="0.01" value={item.price} onChange={(e) => changePricing(group, index, e.target.value)} /></div>)}</div></article>)}</div></section>
    <section><h2 className="mb-3 text-xl font-black text-park-dark">Ambientes para eventos</h2><p className="mb-3 text-sm text-park-muted">Precio base del ambiente; el cliente podrá personalizar menú, bebidas, producción y otros complementos.</p><div className="grid gap-4 md:grid-cols-3">{form.eventSpaces.map((space, index) => <article className="rounded-card border border-park-border bg-white p-5 shadow-card" key={space.id}><h3 className="font-black text-park-dark">{space.name}</h3><p className="mb-4 text-xs text-park-muted">{space.description}</p><div className="space-y-3"><Input label="Nombre" value={space.name} onChange={(e) => change("eventSpaces", index, "name", e.target.value)} /><Input label="Capacidad" type="number" min="1" value={space.capacity} onChange={(e) => change("eventSpaces", index, "capacity", e.target.value)} /><Input label="Base del ambiente (S/)" type="number" min="0" step="0.01" value={space.basePrice} onChange={(e) => change("eventSpaces", index, "basePrice", e.target.value)} /></div><p className="mt-3 text-xs font-bold text-park-muted">Actual: {money(space.basePrice)}</p></article>)}</div></section>
    <div className="sticky bottom-4 flex justify-end"><Button type="submit" loading={saving} icon={Save}>Guardar todas las tarifas</Button></div>
  </form>;
}
