import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { BedDouble, CalendarCheck, Car, Plus, Save, Sparkles, Trash2, Waves } from "lucide-react";
import { Alert, Button, Input, PageHeader } from "../../components/ui";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { Toast } from "../../components/Toast";
import { useFetch } from "../../hooks/useFetch";
import { api } from "../../services/api";

const icons = { HOSPEDAJE: BedDouble, PISCINA: Waves, MIRADOR: Sparkles, EVENTOS: CalendarCheck };
const labels = { TODOS: "Todos", HOSPEDAJE: "Hospedaje", PISCINA: "Piscina", MIRADOR: "Mirador", EVENTOS: "Eventos", COMPLEMENTOS: "Complementos" };
const pricingGroupLabels = { HOSPEDAJE: "Planes de hospedaje", PISCINA: "Entradas de piscina", MIRADOR: "Entradas de mirador", EXTRAS_HOSPEDAJE: "Extras de hospedaje", EXTRAS_PISCINA: "Extras de piscina", EXTRAS_MIRADOR: "Extras de mirador", EQUIPO_EVENTO: "Equipos para eventos" };

export function CommercialSettingsPage() {
  const { data, loading, error, reload } = useFetch("/admin/commercial-settings", { initialData: null, cacheTime: 0 });
  const [form, setForm] = useState(null); const [filter, setFilter] = useState("TODOS"); const [activePricingGroup, setActivePricingGroup] = useState("HOSPEDAJE"); const [savingKey, setSavingKey] = useState(""); const [notice, setNotice] = useState(""); const [failure, setFailure] = useState(""); const [draftDirty, setDraftDirty] = useState(false);
  // El catálogo se actualiza en segundo plano. No puede pisar lo que el dueño
  // está escribiendo al cambiar de filtro, mientras aún no presiona Guardar.
  useEffect(() => { if (data && !draftDirty) setForm(structuredClone(data)); }, [data, draftDirty]);
  if (loading || !form) return <LoadingSpinner label="Cargando catálogo de servicios..." />;
  if (error) return <Alert tone="danger" title="No se pudieron cargar los servicios">{error.message}</Alert>;
  const updateDraft = (updater) => { setDraftDirty(true); setForm(updater); };
  const change = (section, index, key, value) => updateDraft((current) => ({ ...current, [section]: current[section].map((item, row) => row === index ? { ...item, [key]: value } : item) }));
  const changePricing = (group, index, key, value) => updateDraft((current) => ({ ...current, experiencePricing: { ...current.experiencePricing, [group]: current.experiencePricing[group].map((item, row) => row === index ? { ...item, [key]: value } : item) } }));
  const addPricing = (group) => updateDraft((current) => ({ ...current, experiencePricing: { ...current.experiencePricing, [group]: [...(current.experiencePricing[group] || []), { id: `CUSTOM_${Date.now()}`, name: "Nuevo adicional", description: "Describe lo que incluye", price: 0, active: true }] } }));
  const removePricing = (group, index) => updateDraft((current) => ({ ...current, experiencePricing: { ...current.experiencePricing, [group]: current.experiencePricing[group].filter((_, row) => row !== index) } }));
  async function saveSection(key, body, label) { setSavingKey(key); setFailure(""); try { await api("/admin/commercial-settings", { method: "PUT", body: structuredClone(body) }); setNotice(`${label} guardado. El cambio ya se aplicará a las nuevas reservas.`); } catch (err) { setFailure(err.message); } finally { setSavingKey(""); } }
  const visibleServices = form.services.filter((service) => filter === "TODOS" || service.code === filter);
  const showHotel = filter === "TODOS" || filter === "HOSPEDAJE"; const showEvents = filter === "TODOS" || filter === "EVENTOS"; const showExtras = filter === "TODOS" || filter === "COMPLEMENTOS";
  return <div className="catalog-modern space-y-6 pb-10"><Toast message={notice} onClose={() => setNotice("")} /><PageHeader eyebrow="Catálogo · reservas" title="Servicios" description="Cada tarjeta se guarda por separado. Puedes modificar un precio sin arriesgar los cambios de los demás servicios." />{failure ? <Alert tone="danger" title="No se pudo guardar">{failure}</Alert> : null}
    <section className="catalog-modern__guide"><Sparkles size={22}/><div><strong>Primero elige un servicio</strong><span>Usa los filtros para editar solo aquello que necesitas. El precio que cambies se aplicará a las nuevas reservas, nunca a una reserva ya pagada.</span></div></section>
    <nav className="catalog-modern__filters" aria-label="Filtrar servicios">{Object.entries(labels).map(([value, label]) => <button className={filter === value ? "is-active" : ""} key={value} onClick={() => setFilter(value)} type="button">{label}</button>)}</nav>
    {visibleServices.length ? <section><div className="catalog-modern__heading"><p>SERVICIOS PARA EL CLIENTE</p><h2>Precio y capacidad</h2><span>El cliente verá estos nombres, textos y precios al realizar una reserva.</span></div><div className="catalog-modern__service-grid">{visibleServices.map((service) => { const index = form.services.findIndex((item) => item.code === service.code); const Icon = icons[service.code] || Sparkles; const key = `service-${service.code}`; return <article key={service.code}><span><Icon size={21}/></span><div><p>{labels[service.code]}</p><h3>{service.name}</h3><small>{service.code === "HOSPEDAJE" ? "La tarifa final depende del tipo de habitación." : "Precio base que verá el cliente."}</small></div><div className="catalog-modern__field-grid"><Input label="Nombre visible" value={service.name} onChange={(event) => change("services", index, "name", event.target.value)} /><Input label="Descripción visible" value={service.description || ""} onChange={(event) => change("services", index, "description", event.target.value)} /><Input label="Precio base (S/)" type="number" min="0" step="0.01" value={service.price} onChange={(event) => change("services", index, "price", event.target.value)} />{service.capacity ? <Input label="Personas por horario" type="number" min="1" value={service.capacity} onChange={(event) => change("services", index, "capacity", event.target.value)} /> : null}</div><div className="mt-4 flex justify-end"><Button type="button" size="sm" icon={Save} loading={savingKey === key} onClick={() => saveSection(key, { services: [service] }, service.name)}>Guardar solo {service.name}</Button></div></article>; })}</div></section> : null}
    {showHotel ? <section><div className="catalog-modern__heading"><p>HOSPEDAJE</p><h2>Tipos de habitación</h2><span>Un cambio de precio se aplicará a todas las habitaciones de ese tipo.</span></div><div className="catalog-modern__room-grid">{form.roomTypes.map((room, index) => { const key=`room-${room.name}`; return <article key={room.name}><BedDouble size={20}/><h3>{room.name}</h3><p>{room.rooms} habitaciones · hasta {room.capacity} huésped(es)</p><Input label="Precio por noche (S/)" type="number" min="0" step="0.01" value={room.price} onChange={(event) => change("roomTypes", index, "price", event.target.value)} /><div className="mt-3 flex justify-end"><Button type="button" size="sm" icon={Save} loading={savingKey===key} onClick={() => saveSection(key,{roomTypes:[room]},room.name)}>Guardar</Button></div></article>; })}</div></section> : null}
    {showEvents ? <section><div className="catalog-modern__heading"><p>EVENTOS</p><h2>Ambientes disponibles</h2><span>Define el nombre, capacidad y precio base de cada ambiente.</span></div><div className="catalog-modern__room-grid">{form.eventSpaces.map((space, index) => { const key=`event-${space.id}`; return <article key={space.id}><CalendarCheck size={20}/><h3>{space.name}</h3><p>{space.description}</p><Input label="Nombre" value={space.name} onChange={(event) => change("eventSpaces", index, "name", event.target.value)} /><Input label="Capacidad" type="number" min="1" value={space.capacity} onChange={(event) => change("eventSpaces", index, "capacity", event.target.value)} /><Input label="Precio base (S/)" type="number" min="0" step="0.01" value={space.basePrice} onChange={(event) => change("eventSpaces", index, "basePrice", event.target.value)} /><div className="mt-3 flex justify-end"><Button type="button" size="sm" icon={Save} loading={savingKey===key} onClick={() => saveSection(key,{eventSpaces:[space]},space.name)}>Guardar</Button></div></article>; })}</div></section> : null}
    {showExtras ? <section className="catalog-modern__split">
      <article><div className="catalog-modern__heading"><p>COMPLEMENTOS</p><h2>Cochera</h2><span>Tarifas adicionales por vehículo.</span></div><div className="catalog-modern__field-grid">{Object.entries(form.parkingRates || {}).map(([type, price]) => <Input key={type} label={`${type[0]}${type.slice(1).toLowerCase()} · S/`} type="number" min="0" step="0.01" value={price} onChange={(event) => updateDraft((current) => ({ ...current, parkingRates: { ...current.parkingRates, [type]: event.target.value } }))} />)}</div><div className="mt-4 flex justify-end"><Button type="button" size="sm" icon={Save} loading={savingKey === "parking"} onClick={() => saveSection("parking", { parkingRates: form.parkingRates }, "Tarifas de cochera")}>Guardar cochera</Button></div></article>
      <article><div className="catalog-modern__heading"><p>PLANES Y EXTRAS</p><h2>Adicionales de reserva</h2><span>Crea, describe, pausa o elimina opciones sin una lista interminable.</span></div><div className="catalog-modern__pricing-tabs">{Object.keys(form.experiencePricing || {}).map((group) => <button className={activePricingGroup === group ? "is-active" : ""} key={group} onClick={() => setActivePricingGroup(group)} type="button">{pricingGroupLabels[group] || group}</button>)}</div><div className="catalog-modern__pricing-actions"><strong>{pricingGroupLabels[activePricingGroup] || activePricingGroup}</strong><button onClick={() => addPricing(activePricingGroup)} type="button"><Plus size={15}/>Agregar opción</button></div><div className="catalog-modern__pricing-editor">{(form.experiencePricing?.[activePricingGroup] || []).map((item, index) => <div className="catalog-modern__pricing-field" key={`${activePricingGroup}-${item.code || item.id}`}><div className="catalog-modern__pricing-head"><Input label="Nombre" value={item.name} onChange={(event) => changePricing(activePricingGroup, index, "name", event.target.value)} /><button aria-label={`Eliminar ${item.name}`} className="catalog-modern__delete-pricing" onClick={() => removePricing(activePricingGroup, index)} type="button"><Trash2 size={15}/></button></div><Input label="Descripción" value={item.description || ""} onChange={(event) => changePricing(activePricingGroup, index, "description", event.target.value)} /><div className="catalog-modern__pricing-bottom"><Input label="Precio S/" type="number" min="0" step="0.01" value={item.price} onChange={(event) => changePricing(activePricingGroup, index, "price", event.target.value)} /><label className="catalog-modern__active-toggle"><input checked={item.active !== false} onChange={(event) => changePricing(activePricingGroup, index, "active", event.target.checked)} type="checkbox"/><span>{item.active !== false ? "Visible" : "Oculto"}</span></label></div></div>)}</div><div className="mt-4 flex justify-end"><Button type="button" size="sm" icon={Save} loading={savingKey === `pricing-${activePricingGroup}`} onClick={() => saveSection(`pricing-${activePricingGroup}`, { experiencePricing: { [activePricingGroup]: form.experiencePricing?.[activePricingGroup] || [] } }, pricingGroupLabels[activePricingGroup] || activePricingGroup)}>Guardar este grupo</Button></div></article>
    </section> : null}
    <section className="catalog-modern__footer-link"><Car size={20}/><div><strong>¿Quieres cambiar fotos o descripciones?</strong><span>Hazlo en Contenido e imágenes; así los precios y la presentación al cliente no se mezclan.</span></div><Link to="/admin/contenido">Abrir contenido e imágenes</Link></section>
  </div>;
}
