import { RefreshCw, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import { Alert, Button, PageHeader } from "../../components/ui";
import { EmptyState } from "../../components/EmptyState";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { useFetch } from "../../hooks/useFetch";
import { api } from "../../services/api";
import { useState } from "react";

export function DataIntegrityPage() {
  const { data = { summary: {}, checks: [] }, loading, reload } = useFetch("/data-integrity", { initialData: { summary: {}, checks: [] } });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function sanitize() { setBusy(true); try { const result = await api("/data-integrity/sanitize", { method: "POST", body: {} }); setMessage(`Saneamiento aplicado: ${result.repairedOrders?.length || 0} pedidos y ${result.repairedStays?.length || 0} estancias revisados.`); await reload(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  if (loading) return <LoadingSpinner/>;
  return <div className="space-y-5"><PageHeader eyebrow="Administración / control de calidad" title="Integridad y saneamiento" description="Detecta datos que afectan la operación y aplica solo correcciones seguras e idempotentes." actions={<div className="flex gap-2"><Button variant="secondary" icon={RefreshCw} onClick={reload}>Actualizar</Button><Button icon={Sparkles} loading={busy} onClick={sanitize}>Saneamiento seguro</Button></div>}/>{message ? <Alert tone={message.startsWith("Saneamiento") ? "success" : "danger"} title="Resultado">{message}</Alert> : null}<section className="grid gap-3 sm:grid-cols-3"><Metric label="Críticos" value={data.summary.critical || 0} tone="red"/><Metric label="Advertencias" value={data.summary.warnings || 0} tone="amber"/><Metric label="Controles sanos" value={data.summary.healthy || 0} tone="green"/></section><div className="grid gap-4 xl:grid-cols-2">{data.checks.map((check) => <article key={check.code} className="rounded-card border border-park-border bg-white p-5 shadow-card"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-park-dark">{check.title}</h2><p className="mt-1 text-xs text-park-muted">{check.autoFixable ? "Se puede sanear automáticamente sin borrar historial." : "Requiere revisión del responsable antes de modificar datos."}</p></div><Badge severity={check.severity}/></div>{!check.items?.length ? <div className="mt-4 flex items-center gap-2 rounded-lg bg-park-green-soft p-3 text-sm font-bold text-park-green"><ShieldCheck size={16}/> Sin hallazgos.</div> : <ul className="mt-4 space-y-2">{check.items.slice(0,8).map((row) => <li className="rounded-lg bg-park-bg p-3 text-sm" key={row.id}><b className="text-park-dark">{row.label}</b><span className="block text-xs text-park-muted">{row.detail}</span></li>)}</ul>}{check.items?.length > 8 ? <p className="mt-3 text-xs font-bold text-park-muted">Y {check.items.length - 8} hallazgos más.</p> : null}</article>)}</div>{!data.checks.length ? <EmptyState title="Sin controles" description="Actualiza el panel para ejecutar la revisión."/> : null}</div>;
}
function Metric({ label, value, tone }) { const colors={red:"border-red-200 bg-red-50 text-red-700",amber:"border-amber-200 bg-amber-50 text-amber-700",green:"border-emerald-200 bg-emerald-50 text-emerald-700"};return <article className={`rounded-card border p-4 ${colors[tone]}`}><p className="text-3xl font-black">{value}</p><p className="text-sm font-bold">{label}</p></article>; }
function Badge({ severity }) { const map={OK:["Sano","bg-emerald-100 text-emerald-700"],WARNING:["Atención","bg-amber-100 text-amber-700"],CRITICAL:["Crítico","bg-red-100 text-red-700"]};const [label,classes]=map[severity]||map.WARNING;return <span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-black ${classes}`}>{severity!=="OK"?<TriangleAlert size={13}/>:<ShieldCheck size={13}/>} {label}</span>; }
