import { useMemo, useState } from "react";
import { CheckCircle2, ChefHat, CirclePause, Clock3, PackageSearch, Save, Search, UtensilsCrossed, Wine } from "lucide-react";
import { Alert, Button, Input, PageHeader } from "../../components/ui";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { Toast } from "../../components/Toast";
import { useFetch } from "../../hooks/useFetch";
import { api } from "../../services/api";

const money = (value) => `S/ ${Number(value || 0).toLocaleString("es-PE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function FoodBeverageControlPage() {
  const menu = useFetch("/admin/menu-items", { initialData: [], pollInterval: 30000 });
  const [area, setArea] = useState("TODOS"); const [saleState, setSaleState] = useState("TODOS"); const [category, setCategory] = useState("TODAS"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState(null); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [failure, setFailure] = useState("");
  const menuItems = Array.isArray(menu.data) ? menu.data : [];
  const categories = useMemo(() => [...new Set(menuItems.filter((item) => area === "TODOS" || item.area === area).map((item) => item.category || "Sin categoría"))].sort(), [menuItems, area]);
  const filtered = useMemo(() => menuItems.filter((item) => (area === "TODOS" || item.area === area) && (saleState === "TODOS" || (saleState === "EN_VENTA" ? item.salesEnabled === true : item.salesEnabled !== true)) && (category === "TODAS" || (item.category || "Sin categoría") === category) && `${item.name} ${item.category} ${item.code}`.toLowerCase().includes(query.toLowerCase())), [menuItems, area, saleState, category, query]);
  if (menu.loading) return <LoadingSpinner label="Cargando carta y productos..." />;
  if (menu.error) return <Alert tone="danger" title="No se pudo cargar la carta">{menu.error.message}</Alert>;
  const salesEnabled = menuItems.filter((item) => item.salesEnabled === true).length;
  async function toggleSale(item) { setSaving(true); setFailure(""); try { const next = item.salesEnabled !== true; await api(`/admin/menu-items/${item.id}/sales-enabled`, { method: "PATCH", body: { salesEnabled: next } }); await menu.reload(); setNotice(`${item.name}: venta ${next ? "habilitada" : "pausada"}.`); } catch (error) { setFailure(error.message); } finally { setSaving(false); } }
  async function saveProduct(event) { event.preventDefault(); if (!selected) return; setSaving(true); setFailure(""); try { await api(`/admin/menu-items/${selected.id}`, { method: "PUT", body: selected }); await menu.reload(); setSelected(null); setNotice("El producto fue actualizado. Los nuevos pedidos usarán el precio y la información nueva."); } catch (error) { setFailure(error.message); } finally { setSaving(false); } }
  return <main className="catalog-modern space-y-6 pb-10"><Toast message={notice} onClose={() => setNotice("")} /><PageHeader eyebrow="Catálogo · alimentos y bebidas" title="Carta" description="Administra los platos y bebidas que el cliente puede ver y pedir. Los pedidos, compras y cierres se gestionan en Operación e Inventario." />{failure ? <Alert tone="danger" title="No se pudo guardar">{failure}</Alert> : null}
    <section className="catalog-modern__guide"><UtensilsCrossed size={22}/><div><strong>Una decisión simple por producto</strong><span>Busca un plato o bebida, revisa su precio y luego habilita o pausa la venta al cliente. Las recetas y gramajes se mantienen protegidos en Inventario.</span></div></section>
    <section className="catalog-modern__catalog-summary"><div><span>{menuItems.length}</span><strong>productos en carta</strong></div><div><span>{salesEnabled}</span><strong>habilitados para vender</strong></div><div><span>{menuItems.filter((item) => item.area === "RESTAURANTE").length}</span><strong>de Restaurante</strong></div><div><span>{menuItems.filter((item) => item.area === "BARTENDER").length}</span><strong>de Bar</strong></div></section>
    <section className="catalog-modern__filter-panel"><label><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar plato o bebida" /></label><div className="catalog-modern__filter-group"><span>Área</span><div className="catalog-modern__filters">{[["TODOS", "Toda la carta"], ["RESTAURANTE", "Restaurante"], ["BARTENDER", "Bar"]].map(([value, label]) => <button className={area === value ? "is-active" : ""} key={value} onClick={() => { setArea(value); setCategory("TODAS"); }} type="button">{label}</button>)}</div></div><div className="catalog-modern__filter-group"><span>Venta</span><div className="catalog-modern__filters">{[["TODOS", "Cualquier estado"], ["EN_VENTA", "Disponible"], ["PAUSADOS", "Pausada"]].map(([value, label]) => <button className={saleState === value ? "is-active" : ""} key={value} onClick={() => setSaleState(value)} type="button">{label}</button>)}</div></div><label className="catalog-modern__select-label"><span>Categoría</span><select aria-label="Filtrar por categoría" value={category} onChange={(event) => setCategory(event.target.value)}><option value="TODAS">Todas</option>{categories.map((item) => <option value={item} key={item}>{item}</option>)}</select></label></section>
    <section><div className="catalog-modern__heading"><p>PRODUCTOS</p><h2>{filtered.length} resultado(s)</h2><span>Publicado significa que aparece en la carta. Para que el cliente lo pida, la venta y el stock de su receta deben estar listos.</span></div><div className="catalog-modern__product-list">{filtered.map((item) => <article key={item.id}><img src={item.image || ""} alt=""/><div className="catalog-modern__product-main"><strong>{item.name}</strong><span>{item.area === "BARTENDER" ? "Bar" : "Restaurante"} · {item.category}</span><small>{money(item.price)} · {item.prepMinutes || 0} min de preparación</small></div><div className="catalog-modern__product-status"><span className="is-published"><CheckCircle2 size={14}/>Publicado</span><span className={item.salesEnabled === true ? "is-selling" : "is-paused"}>{item.salesEnabled === true ? <CheckCircle2 size={14}/> : <CirclePause size={14}/>}{item.salesEnabled === true ? "Venta activa" : "Venta pausada"}</span>{item.salesEnabled === true ? <span className={item.available ? "is-selling" : "is-paused"}>{item.available ? <CheckCircle2 size={14}/> : <CirclePause size={14}/>}{item.available ? `${item.availablePortions} porciones listas` : `Sin stock${item.limitingIngredient?.productName ? `: ${item.limitingIngredient.productName}` : " o receta activa"}`}</span> : null}</div><div className="catalog-modern__product-actions"><Button size="sm" variant="secondary" onClick={() => setSelected({ ...item })}>Editar</Button><Button size="sm" disabled={saving} onClick={() => toggleSale(item)}>{item.salesEnabled === true ? "Pausar" : "Habilitar"}</Button></div></article>)}</div>{!filtered.length ? <div className="catalog-modern__empty"><PackageSearch size={25}/><strong>No encontramos productos con ese filtro</strong><span>Prueba cambiando el área, el estado de venta o la búsqueda.</span></div> : null}</section>
    {selected ? <div className="catalog-modern__drawer-backdrop" onMouseDown={() => setSelected(null)}><form className="catalog-modern__drawer" onMouseDown={(event) => event.stopPropagation()} onSubmit={saveProduct}><div><p>EDITAR PRODUCTO</p><h2>{selected.name}</h2><span>Cambia la información comercial. La receta y los gramajes se editan en su módulo técnico.</span></div><Input label="Nombre visible" value={selected.name} onChange={(event) => setSelected({ ...selected, name: event.target.value })} /><Input label="Categoría" value={selected.category || ""} onChange={(event) => setSelected({ ...selected, category: event.target.value })} /><Input label="Precio de venta (S/)" type="number" min="0" step="0.01" value={selected.price} onChange={(event) => setSelected({ ...selected, price: event.target.value })} /><Input label="Tiempo de preparación (minutos)" type="number" min="0" value={selected.prepMinutes || 0} onChange={(event) => setSelected({ ...selected, prepMinutes: event.target.value })} /><Input label="Descripción visible" value={selected.description || ""} onChange={(event) => setSelected({ ...selected, description: event.target.value })} /><Input label="URL de imagen" type="url" value={selected.image || ""} onChange={(event) => setSelected({ ...selected, image: event.target.value })} /><div className="catalog-modern__drawer-note"><Clock3 size={17}/><span>Para cambiar ingredientes, gramajes, ml o costos, abre Recetas técnicas desde Inventario.</span></div><div className="catalog-modern__drawer-actions"><Button type="button" variant="secondary" onClick={() => setSelected(null)}>Cancelar</Button><Button type="submit" loading={saving} icon={Save}>Guardar producto</Button></div></form></div> : null}
  </main>;
}
