import { AlertTriangle, BedDouble, CalendarCheck, CheckCircle2, ClipboardCheck, DoorOpen, LogIn, LogOut, Sparkles, Wrench } from "lucide-react";
import { Link } from "react-router-dom";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { StatusBadge } from "../../components/StatusBadge";
import { Button, PageHeader } from "../../components/ui";
import { useFetch } from "../../hooks/useFetch";
import { currentHotelDateKey, formatHotelDate, hotelDateKey, isHotelToday } from "../../utils/hotelDate";

const money = (value) => `S/ ${Number(value || 0).toFixed(2)}`;

export function HotelHomePage() {
  const { data: reservations, loading: loadingReservations } = useFetch("/reservations", { initialData: [] });
  const { data: roomData, loading: loadingRooms } = useFetch("/rooms", { initialData: { rooms: [] } });
  const { data: cleaningTasks, loading: loadingCleaning } = useFetch("/reception/tasks", { initialData: [] });
  const { data: reportData, loading: loadingReports } = useFetch("/reports", { initialData: { reports: [] } });
  if (loadingReservations || loadingRooms || loadingCleaning || loadingReports) return <LoadingSpinner label="Cargando operación de hospedaje..." />;
  const rows = Array.isArray(reservations) ? reservations : [];
  const rooms = roomData?.rooms || [];
  const today = currentHotelDateKey();
  const arrivals = rows.filter((item) => !item.stay && hotelDateKey(item.checkInDate) <= today && hotelDateKey(item.checkOutDate) > today && !["CANCELADA", "COMPLETADA", "NO_SHOW"].includes(item.status));
  const departures = rows.filter((item) => item.stay && isHotelToday(item.checkOutDate));
  const staying = rows.filter((item) => item.stay && item.status === "CHECKED_IN");
  const pendingBalance = arrivals.filter((item) => Number(item.balance || 0) > 0);
  const cleaning = (cleaningTasks || []).filter((item) => !["FINALIZADA", "CANCELADA"].includes(item.status));
  const maintenance = (reportData?.reports || []).filter((item) => item.requiresMaintenance && !["RESUELTO", "CANCELADO"].includes(item.status));
  const kpis = [
    [LogIn, "Llegadas por atender", arrivals.length, "bg-park-gold-soft text-park-dark", "/hotel/movimientos"],
    [LogOut, "Salidas hoy", departures.length, "bg-park-green-soft text-park-green", "/hotel/movimientos"],
    [BedDouble, "Huéspedes alojados", staying.length, "bg-park-green-soft text-park-green", "/clientes"],
    [CheckCircle2, "Habitaciones listas", rooms.filter((item) => item.status === "LIBRE").length, "bg-park-green-soft text-park-green", "/hotel/habitaciones"]
  ];
  return <main className="hotel-modern space-y-5 pb-10"><PageHeader eyebrow="Hotel · operación de hospedaje" title="¿Qué necesita atención hoy?" description="Este panel es exclusivo de huéspedes y habitaciones. La ficha de cada persona se consulta en Sistema > Clientes." actions={<><Button as={Link} to="/hotel/reservas?nueva=1" icon={CalendarCheck}>Nueva reserva</Button><Button as={Link} to="/clientes" variant="secondary">Ver clientes</Button></>}/>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([Icon, label, value, tone, href]) => <Link className="rounded-card border border-park-border bg-white p-4 shadow-card transition hover:-translate-y-0.5 hover:border-park-gold" key={label} to={href}><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={19}/></span><strong className="mt-3 block font-display text-3xl text-park-dark">{value}</strong><span className="text-sm font-semibold text-park-muted">{label}</span></Link>)}</section>
    <section className="rounded-card border border-park-gold/40 bg-park-gold-soft/40 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 text-park-gold-deep" size={20}/><div><h2 className="font-black text-park-dark">Atención prioritaria</h2><div className="mt-2 flex flex-wrap gap-2">{[[pendingBalance.length, "Llegadas con saldo pendiente", "/hotel/movimientos"], [cleaning.length, "Habitaciones esperando limpieza", "/hotel/limpieza"], [maintenance.length, "Incidencias de mantenimiento abiertas", "/hotel/mantenimiento"]].map(([count, label, href]) => <Link className="rounded-full border border-park-gold/40 bg-white px-3 py-1.5 text-xs font-black text-park-dark hover:border-park-green" key={label} to={href}>{count} · {label}</Link>)}</div></div></div></section>
    <section className="grid gap-5 xl:grid-cols-2"><HotelList title="Llegadas por atender" description="Confirma pago, habitación lista y datos antes del ingreso." empty="No hay llegadas pendientes." rows={arrivals.slice(0, 6)} action="Abrir llegadas y salidas" href="/hotel/movimientos" render={(item) => <><Guest item={item}/><span className="text-sm font-black text-park-dark">Hab. {item.room?.number || "-"}</span><StatusBadge value={Number(item.balance || 0) > 0 ? "PENDIENTE_PAGO" : item.status}/></>}/><HotelList title="Salidas de hoy" description="Revisa consumos y saldo antes de enviar la habitación a limpieza." empty="No hay salidas pendientes." rows={departures.slice(0, 6)} action="Abrir llegadas y salidas" href="/hotel/movimientos" render={(item) => <><Guest item={item}/><span className="text-sm font-black text-park-dark">Hab. {item.room?.number || "-"}</span><span className={Number(item.balance || 0) > 0 ? "font-black text-park-danger" : "font-black text-park-green"}>{Number(item.balance || 0) > 0 ? `Saldo ${money(item.balance)}` : "Cuenta al día"}</span></>}/></section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-card border border-park-border bg-white shadow-card"><header className="flex items-start justify-between border-b border-park-border p-5"><div><p className="text-xs font-black uppercase tracking-wide text-park-gold">Estado de habitaciones</p><h2 className="font-display text-xl text-park-dark">Disponibilidad del hotel</h2></div><Button as={Link} size="sm" to="/hotel/habitaciones" variant="secondary">Ver habitaciones</Button></header><div className="grid grid-cols-2 gap-px bg-park-border sm:grid-cols-3">{[["LIBRE", "Libres"], ["RESERVADA", "Reservadas"], ["OCUPADA", "Ocupadas"], ["EN_LIMPIEZA", "En limpieza"], ["MANTENIMIENTO", "Mantenimiento"], ["FUERA_SERVICIO", "Fuera de servicio"]].map(([status, label]) => <div className="bg-white p-4" key={status}><span className="text-xs font-semibold text-park-muted">{label}</span><strong className="mt-1 block font-display text-2xl text-park-dark">{rooms.filter((room) => room.status === status).length}</strong></div>)}</div></article><article className="rounded-card border border-park-border bg-white p-5 shadow-card"><p className="text-xs font-black uppercase tracking-wide text-park-gold">Flujo conectado</p><h2 className="font-display text-xl text-park-dark">De reserva a habitación lista</h2><div className="mt-4 space-y-3 text-sm">{[[CalendarCheck, "Reserva", "Asignación y pago"], [DoorOpen, "Llegada", "Check-in y estadía"], [LogOut, "Salida", "Cuenta cerrada"], [Sparkles, "Limpieza", "Evidencias y liberación"], [Wrench, "Mantenimiento", "Bloqueo si es necesario"]].map(([Icon, title, text]) => <div className="flex gap-3" key={title}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-park-green-soft text-park-green"><Icon size={16}/></span><p><strong className="block text-park-dark">{title}</strong><span className="text-park-muted">{text}</span></p></div>)}</div></article></section>
  </main>;
}

function Guest({ item }) { return <div><strong className="block text-sm text-park-dark">{item.client?.firstName} {item.client?.lastName}</strong><span className="text-xs text-park-muted">{item.code} · {formatHotelDate(item.checkInDate)}</span></div>; }
function HotelList({ title, description, rows, empty, href, action, render }) { return <article className="rounded-card border border-park-border bg-white shadow-card"><header className="flex items-start justify-between gap-3 border-b border-park-border p-5"><div><h2 className="font-display text-xl text-park-dark">{title}</h2><p className="mt-1 text-sm text-park-muted">{description}</p></div><Button as={Link} size="sm" to={href} variant="secondary">Ver todo</Button></header><div className="divide-y divide-park-border">{rows.length ? rows.map((item) => <div className="grid grid-cols-[1fr_auto] gap-3 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center" key={item.id}>{render(item)}</div>) : <p className="p-6 text-center text-sm text-park-muted">{empty}</p>}</div><Link className="flex items-center justify-center gap-2 border-t border-park-border p-3 text-sm font-black text-park-green hover:bg-park-green-soft" to={href}><ClipboardCheck size={16}/>{action}</Link></article>; }
