import { AlertTriangle, BedDouble, CalendarCheck, CheckCircle2, ClipboardCheck, DoorOpen, LogIn, LogOut, Search, Sparkles, UsersRound, Wrench } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useMemo } from "react";
import { LoadingSpinner } from "../../components/LoadingSpinner";
import { StatusBadge } from "../../components/StatusBadge";
import { Button, PageHeader } from "../../components/ui";
import { useFetch } from "../../hooks/useFetch";
import { currentHotelDateKey, formatHotelDate, hotelDateKey, isHotelToday } from "../../utils/hotelDate";

const views = [["inicio", "Inicio", DoorOpen], ["reservas", "Reservas", CalendarCheck], ["movimientos", "Llegadas y salidas", LogIn], ["habitaciones", "Habitaciones", BedDouble], ["clientes", "Clientes de hotel", UsersRound], ["limpieza", "Limpieza", Sparkles], ["mantenimiento", "Mantenimiento", Wrench]];
const href = (view) => `/hotel?vista=${view}`;
const stayOpen = (item) => item.status === "CHECKED_IN" || item.stay;

export function HotelWorkspacePage() {
  const [params] = useSearchParams(); const view = views.some(([key]) => key === params.get("vista")) ? params.get("vista") : "inicio";
  const { data: reservations, loading: a } = useFetch("/reservations", { initialData: [] });
  const { data: roomData, loading: b } = useFetch("/rooms", { initialData: { rooms: [] } });
  const { data: tasks, loading: c } = useFetch("/reception/tasks", { initialData: [] });
  const { data: reports, loading: d } = useFetch("/reports", { initialData: { reports: [] } });
  if (a || b || c || d) return <LoadingSpinner label="Cargando estación Hotel..."/>;
  const rows = reservations || []; const rooms = roomData?.rooms || []; const cleaning = tasks || []; const incidents = (reports?.reports || []).filter((item) => item.requiresMaintenance).map((item) => item.status === "SOLUCIONADO" ? { ...item, status: "RESUELTO" } : item);
  const today = currentHotelDateKey();
  const arrivals = rows.filter((item) => !stayOpen(item) && hotelDateKey(item.checkInDate) <= today && hotelDateKey(item.checkOutDate) > today && !["CANCELADA", "COMPLETADA", "NO_SHOW"].includes(item.status));
  const departures = rows.filter((item) => stayOpen(item) && isHotelToday(item.checkOutDate));
  const clients = groupClients(rows);
  const content = { inicio: <Today rows={rows} rooms={rooms} arrivals={arrivals} departures={departures} cleaning={cleaning} incidents={incidents}/>, reservas: <Reservations rows={rows}/>, movimientos: <Movements arrivals={arrivals} departures={departures}/>, habitaciones: <Rooms rooms={rooms}/>, clientes: <Clients clients={clients}/>, limpieza: <Cleaning tasks={cleaning}/>, mantenimiento: <Maintenance reports={incidents}/> }[view];
  return <main className="hotel-workspace pb-10"><PageHeader eyebrow="Hotel · operación exclusiva de hospedaje" title={views.find(([key]) => key === view)?.[1]} description="Piscina, mirador y eventos se administran en sus propios módulos; aquí solo se trabaja con huéspedes y habitaciones." actions={<Button as={Link} to="/reservas?nueva=1">Nueva reserva</Button>}/><nav className="hotel-workspace__nav">{views.map(([key, label, Icon]) => <Link className={key === view ? "is-active" : ""} key={key} to={href(key)}><Icon size={17}/>{label}</Link>)}</nav>{content}</main>;
}
function Today({ rows, rooms, arrivals, departures, cleaning, incidents }) { const occupied = rooms.filter((item) => item.status === "OCUPADA").length; return <><section className="hotel-workspace__numbers"><Number icon={LogIn} label="Llegadas por atender" value={arrivals.length}/><Number icon={LogOut} label="Salidas hoy" value={departures.length}/><Number icon={BedDouble} label="Huéspedes alojados" value={occupied}/><Number icon={CheckCircle2} label="Habitaciones listas" value={rooms.filter((item) => item.status === "LIBRE").length}/></section><section className="hotel-workspace__priority"><AlertTriangle size={20}/><div><strong>Atención prioritaria</strong><span>{arrivals.filter((item) => Number(item.balance) > 0).length} llegadas con saldo · {cleaning.filter((item) => item.status !== "FINALIZADA").length} habitaciones en limpieza · {incidents.filter((item) => item.status !== "RESUELTO").length} incidencias abiertas</span></div></section><section className="hotel-workspace__two"><Queue title="Llegadas de hoy" rows={arrivals} empty="No hay llegadas pendientes." kind="arrival"/><Queue title="Salidas de hoy" rows={departures} empty="No hay salidas pendientes." kind="departure"/></section><section className="hotel-workspace__room-state"><div><p>ESTADO FÍSICO</p><h2>Habitaciones</h2></div>{[["LIBRE","Libres"],["RESERVADA","Reservadas"],["OCUPADA","Ocupadas"],["EN_LIMPIEZA","Limpieza"],["MANTENIMIENTO","Mantenimiento"]].map(([status,label]) => <Link key={status} to={href("habitaciones")}><span>{label}</span><strong>{rooms.filter((item) => item.status === status).length}</strong></Link>)}</section></>; }
function Reservations({ rows }) { const groups = [["Hoy", rows.filter((item) => isHotelToday(item.checkInDate))], ["Próximas", rows.filter((item) => hotelDateKey(item.checkInDate) > currentHotelDateKey())], ["Con saldo", rows.filter((item) => Number(item.balance) > 0)]]; return <><section className="hotel-workspace__intro"><CalendarCheck/><div><strong>Agenda de hospedaje</strong><span>Una reserva corresponde a una habitación y a una estadía. No aparecen reservas de piscina, mirador ni eventos.</span></div><Button as={Link} to="/reservas">Administrar reservas</Button></section><section className="hotel-workspace__three">{groups.map(([title, list]) => <article key={title}><header><h2>{title}</h2><span>{list.length}</span></header>{list.slice(0,5).map((item) => <Row item={item} key={item.id}/>) || null}{!list.length ? <p>Sin reservas.</p> : null}</article>)}</section></>; }
function Movements({ arrivals, departures }) { return <section className="hotel-workspace__two"><article className="hotel-workspace__process"><header><span>1</span><div><p>LLEGADAS</p><h2>Ingresar huésped</h2><small>Reserva, pago, habitación lista y check-in.</small></div><Button as={Link} to="/checkin" variant="secondary">Abrir llegadas</Button></header>{arrivals.map((item) => <Row item={item} key={item.id} action="Realizar check-in" to={`/checkin?search=${item.code}`}/>) || null}{!arrivals.length ? <p className="hotel-workspace__empty">No hay llegadas pendientes.</p> : null}</article><article className="hotel-workspace__process"><header><span>2</span><div><p>SALIDAS</p><h2>Finalizar estadía</h2><small>Consumos, saldo, check-out y envío a limpieza.</small></div><Button as={Link} to="/checkout" variant="secondary">Abrir salidas</Button></header>{departures.map((item) => <Row item={item} key={item.id} action="Finalizar salida" to="/checkout"/>) || null}{!departures.length ? <p className="hotel-workspace__empty">No hay salidas pendientes.</p> : null}</article></section>; }
function Rooms({ rooms }) { return <><section className="hotel-workspace__intro"><BedDouble/><div><strong>Tablero físico de habitaciones</strong><span>Selecciona una habitación para crear reserva, seguir limpieza o revisar mantenimiento.</span></div><Button as={Link} to="/habitaciones" variant="secondary">Ver detalle</Button></section><section className="hotel-workspace__rooms">{rooms.map((room) => <Link className={`status-${room.status.toLowerCase()}`} key={room.id} to={room.status === "LIBRE" ? `/reservas?nueva=1&habitacion=${room.id}` : room.status === "EN_LIMPIEZA" ? "/admin/limpieza/pendientes" : room.status === "MANTENIMIENTO" ? "/incidencias" : "/habitaciones"}><strong>{room.number}</strong><span>{room.type?.name}</span><StatusBadge value={room.status}/></Link>)}</section></>; }
function Clients({ clients }) { return <><section className="hotel-workspace__intro"><UsersRound/><div><strong>Clientes exclusivos de hotel</strong><span>Solo se muestran personas con una reserva o estadía de hospedaje.</span></div><Button as={Link} to="/hotel/clientes" variant="secondary">Abrir fichas</Button></section><section className="hotel-workspace__client-list">{clients.slice(0,12).map((client) => <Link key={client.id} to="/hotel/clientes"><div><strong>{client.firstName} {client.lastName}</strong><span>DNI {client.documentNumber}</span></div><div>{client.active ? <><b>Hab. {client.active.room?.number}</b><StatusBadge value="CHECKED_IN"/></> : <><b>{client.upcoming ? `Llega ${formatHotelDate(client.upcoming.checkInDate)}` : "Historial"}</b><StatusBadge value={client.upcoming?.status || "FINALIZADA"}/></>}</div></Link>)}</section></>; }
function Cleaning({ tasks }) { const columns = [["PENDIENTE","Por atender"],["EN_LIMPIEZA","En proceso"],["FINALIZADA","Listas"]]; return <><section className="hotel-workspace__intro"><Sparkles/><div><strong>Limpieza por estado</strong><span>Una habitación se libera únicamente después de que limpieza termine la tarea y se valide el resultado.</span></div><Button as={Link} to="/admin/limpieza/resumen" variant="secondary">Gestionar limpieza</Button></section><section className="hotel-workspace__three">{columns.map(([status,label]) => <article className="hotel-workspace__kanban" key={status}><header><h2>{label}</h2><span>{tasks.filter((item) => item.status === status).length}</span></header>{tasks.filter((item) => item.status === status).slice(0,8).map((item) => <Link key={item.id} to="/admin/limpieza/resumen"><strong>Habitación {item.room?.number || "-"}</strong><span>{item.assignedTo || "Sin asignar"}</span><StatusBadge value={item.status}/></Link>)}</article>)}</section></>; }
function Maintenance({ reports }) { return <><section className="hotel-workspace__intro"><Wrench/><div><strong>Mantenimiento de hotel</strong><span>Una incidencia puede bloquear la venta de una habitación hasta que sea resuelta.</span></div><Button as={Link} to="/incidencias" variant="secondary">Gestionar incidencias</Button></section><section className="hotel-workspace__maintenance">{reports.filter((item) => item.status !== "RESUELTO").map((item) => <Link key={item.id} to="/incidencias"><div><StatusBadge value={item.priority}/><strong>{item.location || "Hotel"}</strong><span>{item.description}</span></div><StatusBadge value={item.status}/></Link>)}{!reports.filter((item) => item.status !== "RESUELTO").length ? <p className="hotel-workspace__empty">No hay incidencias de mantenimiento abiertas.</p> : null}</section></>; }
function Queue({ title, rows, empty, kind }) { return <article className="hotel-workspace__queue"><header><div><p>{kind === "arrival" ? "INGRESOS" : "SALIDAS"}</p><h2>{title}</h2></div><Button as={Link} to={kind === "arrival" ? "/checkin" : "/checkout"} size="sm" variant="secondary">Ver todo</Button></header>{rows.slice(0,6).map((item) => <Row item={item} key={item.id} action={kind === "arrival" ? "Abrir llegada" : "Abrir salida"} to={kind === "arrival" ? `/checkin?search=${item.code}` : "/checkout"}/>) || null}{!rows.length ? <p className="hotel-workspace__empty">{empty}</p> : null}</article>; }
function Row({ item, to, action }) { return <div className="hotel-workspace__row"><div><strong>{item.client?.firstName} {item.client?.lastName}</strong><span>{item.code} · Hab. {item.room?.number || "-"} · {formatHotelDate(item.checkInDate)}</span></div><div><StatusBadge value={Number(item.balance || 0) > 0 ? "PENDIENTE_PAGO" : item.status}/>{action ? <Link to={to}>{action}</Link> : null}</div></div>; }
function Number({ icon: Icon, label, value }) { return <article><span><Icon size={18}/></span><strong>{value}</strong><p>{label}</p></article>; }
function groupClients(rows) { return Object.values(rows.reduce((result, item) => { if (!item.client) return result; result[item.client.id] ||= { ...item.client, reservations: [] }; result[item.client.id].reservations.push(item); return result; }, {})).map((client) => ({ ...client, active: client.reservations.find(stayOpen), upcoming: client.reservations.find((item) => ["CONFIRMADA","PENDIENTE"].includes(item.status)) })); }
