import { randomUUID } from "node:crypto";
import { db } from "./db.js";

const n=v=>Number(v||0), r6=v=>Math.round((n(v)+Number.EPSILON)*1e6)/1e6;
function fail(status,message){const e=new Error(message);e.status=status;throw e;}
async function tx(work){const c=await db.connect();try{await c.query("BEGIN");const out=await work(c);await c.query("COMMIT");return out;}catch(e){await c.query("ROLLBACK");if(e.code==="23505")fail(409,"Código de botella ya registrado");throw e;}finally{c.release();}}
async function actor(c,id){const s=(await c.query("SELECT data FROM app_state WHERE id=1 FOR UPDATE")).rows[0].data,identity=(s.users||[]).find(x=>n(x.id)===n(id));if(!identity||!["SUPERADMIN","ADMINISTRADOR","BARTENDER"].includes(identity.role))fail(403,"Solo Bar o Administración pueden operar botellas");const user=identity.role==="SUPERADMIN"?{...identity,role:"ADMINISTRADOR",displayRole:"SUPERADMIN"}:identity;return{state:s,user};}
function access(u){if(!["ADMINISTRADOR","BARTENDER"].includes(u.role))fail(403,"Sin permiso de bar");}
async function audit(c,type,id,actorId,data){await c.query("INSERT INTO inventory_audit_events(event_type,entity_type,entity_id,actor_legacy_user_id,after_data,correlation_id) VALUES($1,'BAR_BOTTLE',$2,$3,$4::jsonb,$5)",[type,id,actorId,JSON.stringify(data),`bar-bottle:${id}`]);}
async function bottle(c,id,lock=false){const row=(await c.query(`SELECT b.*,p.name product_name,p.tolerance_percent,p.density_kg_per_l product_density,l.lot_code FROM bar_bottles b JOIN inventory_products p ON p.id=b.product_id LEFT JOIN inventory_lots l ON l.id=b.lot_id WHERE b.id=$1 ${lock?"FOR UPDATE OF b":""}`,[n(id)])).rows[0];if(!row)fail(404,"Botella no encontrada");return row;}
function dto(row){const expected=n(row.expected_content_ml),physical=row.physical_content_ml==null?null:n(row.physical_content_ml),difference=physical==null?null:r6(physical-expected),cost=difference==null?null:r6(difference*n(row.unit_cost_per_ml));return{id:n(row.id),code:row.code,productId:n(row.product_id),productName:row.product_name,lotId:row.lot_id?n(row.lot_id):null,lotCode:row.lot_code,type:row.bottle_type,status:row.status,nominalMl:n(row.nominal_content_ml),initialMl:n(row.initial_content_ml),expectedMl:expected,physicalMl:physical,differenceMl:difference,differenceCost:cost,densityKgPerL:n(row.density_kg_per_l)||n(row.product_density)||null,tareGrams:row.tare_grams==null?null:n(row.tare_grams),unitCostPerMl:n(row.unit_cost_per_ml),openedAt:row.opened_at,closedAt:row.closed_at};}
async function read(c,id){const b=dto(await bottle(c,id));b.services=(await c.query(`SELECT id,service_type "type",target_ml "targetMl",measured_ml "measuredMl",tolerance_ml "toleranceMl",result,cups,notes,served_at "servedAt" FROM bar_bottle_services WHERE bottle_id=$1 ORDER BY id DESC`,[id])).rows;b.measurements=(await c.query(`SELECT method,content_ml "contentMl",gross_weight_grams "grossWeightGrams",tare_grams "tareGrams",density_kg_per_l "densityKgPerL",measured_at "measuredAt" FROM bar_bottle_measurements WHERE bottle_id=$1 ORDER BY id DESC`,[id])).rows;b.expectedCups=b.type==="WINE"?Math.floor(b.expectedMl/150):null;return b;}
async function barWarehouse(c){const w=(await c.query("SELECT id FROM inventory_warehouses WHERE code='BARTENDER' AND active")).rows[0];if(!w)fail(404,"Almacén de bar no encontrado");return w;}
async function post(c,{key,type,productId,lotId,quantity,cost,actorId,sourceId,reason,metadata={},direction="OUT"}){const warehouse=(await barWarehouse(c)).id;return n((await c.query("SELECT post_inventory_movement($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'BAR_BOTTLE',$11,$12,NULL,NULL,FALSE,$13::jsonb) id",[key,type,productId,quantity,direction==="OUT"?warehouse:null,direction==="IN"?warehouse:null,lotId||null,cost,reason,actorId,sourceId,`BOT-${sourceId}`,JSON.stringify(metadata)])).rows[0].id);}

export async function barBottleReferences(user){access(user);const rows=(await db.query(`SELECT b.product_id "productId",p.name "productName",b.lot_id "lotId",l.lot_code "lotCode",b.on_hand "onHand",COALESCE(l.unit_cost,p.average_cost) "unitCost",p.density_kg_per_l "densityKgPerL" FROM inventory_stock_balances b JOIN inventory_products p ON p.id=b.product_id LEFT JOIN inventory_lots l ON l.id=b.lot_id JOIN inventory_warehouses w ON w.id=b.warehouse_id WHERE w.code='BARTENDER' AND b.on_hand-b.reserved>0 ORDER BY p.name`)).rows;return{stock:rows,defaultWineGlassMl:150,methods:["VOLUME","WEIGHT"]};}
export async function listBarBottles(user){access(user);const rows=(await db.query("SELECT b.*,p.name product_name,p.tolerance_percent,p.density_kg_per_l product_density,l.lot_code FROM bar_bottles b JOIN inventory_products p ON p.id=b.product_id LEFT JOIN inventory_lots l ON l.id=b.lot_id WHERE b.status<>'ARCHIVED' ORDER BY b.opened_at DESC")).rows;return Promise.all(rows.map(row=>read(db,row.id)));}
export async function openBarBottle(payload,actorId){return tx(async c=>{const {user}=await actor(c,actorId);const productId=n(payload.productId),lotId=payload.lotId?n(payload.lotId):null,nominal=n(payload.nominalMl),initial=n(payload.initialMl||payload.nominalMl);if(!productId||!nominal||initial<=0||initial>nominal)fail(400,"Contenido nominal e inicial inválidos");const w=await barWarehouse(c);const stock=(await c.query("SELECT b.on_hand,b.reserved,COALESCE(l.unit_cost,p.average_cost) cost,p.density_kg_per_l FROM inventory_stock_balances b JOIN inventory_products p ON p.id=b.product_id LEFT JOIN inventory_lots l ON l.id=b.lot_id WHERE b.warehouse_id=$1 AND b.product_id=$2 AND b.lot_id IS NOT DISTINCT FROM $3 FOR UPDATE OF b",[w.id,productId,lotId])).rows[0];if(!stock||n(stock.on_hand)-n(stock.reserved)<initial)fail(409,"El lote no tiene contenido suficiente para abrir esta botella");const code=String(payload.code||`BOT-${randomUUID().slice(0,8).toUpperCase()}`).trim(),type=["SPIRIT","WINE","OTHER"].includes(payload.type)?payload.type:"SPIRIT";const row=(await c.query(`INSERT INTO bar_bottles(code,product_id,warehouse_id,lot_id,bottle_type,status,nominal_content_ml,initial_content_ml,expected_content_ml,density_kg_per_l,tare_grams,unit_cost_per_ml,opened_by_legacy_user_id,metadata) VALUES($1,$2,$3,$4,$5,'OPEN',$6,$7,$7,$8,$9,$10,$11,$12::jsonb) RETURNING id`,[code,productId,w.id,lotId,type,nominal,initial,payload.densityKgPerL||stock.density_kg_per_l||null,payload.tareGrams||null,n(stock.cost),actorId,JSON.stringify({source:"BAR_CONTROL"})])).rows[0];await audit(c,"OPEN",row.id,actorId,{code,productId,lotId,nominal,initial,type});return read(c,row.id);});}
export async function serveBarBottle(id,payload,actorId){return tx(async c=>{const {user}=await actor(c,actorId);const b=await bottle(c,id,true);if(b.status!=="OPEN")fail(409,"La botella no está abierta");const target=n(payload.targetMl),measured=n(payload.measuredMl??target),tolerance=n(payload.toleranceMl);if(target<=0||measured<0||target>n(b.expected_content_ml)+.000001)fail(400,"Dosificación inválida o contenido esperado insuficiente");const type=payload.type==="WINE_GLASS"?"WINE_GLASS":"DRINK",result=measured>target+tolerance?"OVERPOURED":measured<target-tolerance?"UNDERPOURED":"NORMAL";const service=(await c.query("INSERT INTO bar_bottle_services(bottle_id,service_type,target_ml,measured_ml,tolerance_ml,result,cups,notes,served_by_legacy_user_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) RETURNING id",[b.id,type,target,measured,tolerance,result,type==="WINE_GLASS"?1:0,payload.notes||null,actorId,JSON.stringify({dosageStatus:result})])).rows[0];const movement=await post(c,{key:`bar-service:${service.id}`,type:"BAR_BOTTLE_SERVICE",productId:b.product_id,lotId:b.lot_id,quantity:target,cost:b.unit_cost_per_ml,actorId,sourceId:service.id,reason:`Servicio ${b.code}`,metadata:{bottleId:n(b.id),targetMl:target,measuredMl:measured,result}});await c.query("UPDATE bar_bottle_services SET movement_id=$2 WHERE id=$1",[service.id,movement]);await c.query("UPDATE bar_bottles SET expected_content_ml=GREATEST(0,expected_content_ml-$2),updated_at=NOW() WHERE id=$1",[b.id,target]);await audit(c,"SERVE",b.id,actorId,{serviceId:n(service.id),target,measured,tolerance,result});return read(c,b.id);});}
export async function measureBarBottle(id,payload,actorId){return tx(async c=>{const {user}=await actor(c,actorId);const b=await bottle(c,id,true);if(b.status!=="OPEN")fail(409,"Solo se mide una botella abierta");const method=String(payload.method||"VOLUME").toUpperCase();let content;if(method==="VOLUME")content=n(payload.contentMl);else if(method==="WEIGHT"){const gross=n(payload.grossWeightGrams),tare=payload.tareGrams==null?n(b.tare_grams):n(payload.tareGrams),density=payload.densityKgPerL==null?n(b.density_kg_per_l)||n(b.product_density):n(payload.densityKgPerL);if(gross<=0||tare<=0||gross<tare||density<=0)fail(400,"Peso bruto, tara y densidad son obligatorios para convertir peso a volumen");content=r6((gross-tare)/density);}else fail(400,"Método de medición no válido");if(content<0)fail(400,"Contenido físico inválido");await c.query("INSERT INTO bar_bottle_measurements(bottle_id,method,content_ml,gross_weight_grams,tare_grams,density_kg_per_l,measured_by_legacy_user_id,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[b.id,method,content,method==="WEIGHT"?n(payload.grossWeightGrams):null,method==="WEIGHT"?(payload.tareGrams??b.tare_grams):null,method==="WEIGHT"?(payload.densityKgPerL??b.density_kg_per_l??b.product_density):null,actorId,payload.notes||null]);await c.query("UPDATE bar_bottles SET physical_content_ml=$2,updated_at=NOW() WHERE id=$1",[b.id,content]);await audit(c,"MEASURE",b.id,actorId,{method,content});return read(c,b.id);});}
export async function closeBarBottle(id,payload,actorId){return tx(async c=>{const {user}=await actor(c,actorId);const b=await bottle(c,id,true);if(b.status!=="OPEN")fail(409,"Solo una botella abierta puede cerrarse");if(b.physical_content_ml==null)fail(400,"Registra una medición física antes del cierre");const difference=r6(n(b.physical_content_ml)-n(b.expected_content_ml));let movementId=null;if(Math.abs(difference)>0.000001)movementId=await post(c,{key:`bar-close:${b.id}`,type:"BAR_BOTTLE_CLOSE_ADJUSTMENT",productId:b.product_id,lotId:b.lot_id,quantity:Math.abs(difference),cost:b.unit_cost_per_ml,actorId,sourceId:b.id,reason:`Conciliación botella ${b.code}`,direction:difference<0?"OUT":"IN",metadata:{expectedMl:n(b.expected_content_ml),physicalMl:n(b.physical_content_ml),differenceMl:difference}});await c.query("UPDATE bar_bottles SET status=$2,closed_at=NOW(),closed_by_legacy_user_id=$3,updated_at=NOW() WHERE id=$1",[b.id,n(b.physical_content_ml)<=0.000001?"EMPTY":"CLOSED",actorId]);await audit(c,"CLOSE",b.id,actorId,{difference,movementId});return read(c,b.id);});}
