import { db } from "./db.js";

const n=(value)=>Number(value||0);
const r6=(value)=>Math.round((n(value)+Number.EPSILON)*1_000_000)/1_000_000;
const STATUSES={DRAFT:"BORRADOR",ACTIVE:"VIGENTE",ARCHIVED:"ARCHIVADA"};

function fail(status,message,fieldErrors={}){const error=new Error(message);error.status=status;error.fieldErrors=fieldErrors;throw error;}
async function tx(work){const client=await db.connect();try{await client.query("BEGIN");const result=await work(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");if(error.code==="23505")fail(409,"El código, producto de salida o versión ya existe");throw error;}finally{client.release();}}
async function audit(client,type,recipeId,actorId,reason,beforeData,afterData){await client.query(`INSERT INTO inventory_audit_events(event_type,entity_type,entity_id,actor_legacy_user_id,reason,before_data,after_data,correlation_id) VALUES($1,'TECHNICAL_RECIPE',$2,$3,$4,$5::jsonb,$6::jsonb,$7)`,[type,recipeId,actorId,reason,beforeData?JSON.stringify(beforeData):null,afterData?JSON.stringify(afterData):null,`recipe:${recipeId}`]);}

async function recipeRow(client,id,lock=false){const row=(await client.query(`SELECT * FROM inventory_recipes WHERE id=$1 ${lock?"FOR UPDATE":""}`,[n(id)])).rows[0];if(!row)fail(404,"Receta no encontrada");return row;}
async function versionRow(client,id,lock=false){const row=(await client.query(`SELECT rv.*,r.area_code,r.recipe_type,r.output_product_id,r.legacy_menu_item_id,r.name recipe_name FROM inventory_recipe_versions rv JOIN inventory_recipes r ON r.id=rv.recipe_id WHERE rv.id=$1 ${lock?"FOR UPDATE OF rv":""}`,[n(id)])).rows[0];if(!row)fail(404,"Versión de receta no encontrada");return row;}

async function conversion(client,product,unitId){if(n(unitId)===n(product.base_unit_id))return 1;const direct=(await client.query("SELECT factor FROM inventory_product_conversions WHERE product_id=$1 AND from_unit_id=$2 AND to_unit_id=$3 AND active ORDER BY id DESC LIMIT 1",[product.id,unitId,product.base_unit_id])).rows[0];if(direct)return n(direct.factor);const reverse=(await client.query("SELECT factor FROM inventory_product_conversions WHERE product_id=$1 AND from_unit_id=$2 AND to_unit_id=$3 AND active ORDER BY id DESC LIMIT 1",[product.id,product.base_unit_id,unitId])).rows[0];if(reverse)return 1/n(reverse.factor);const presentation=(await client.query("SELECT conversion_factor FROM inventory_presentations WHERE product_id=$1 AND unit_id=$2 AND active ORDER BY is_default DESC,id LIMIT 1",[product.id,unitId])).rows[0];if(presentation)return n(presentation.conversion_factor);fail(400,`No existe conversión de la unidad elegida a la unidad base para ${product.name}`);}

async function descendantsOfIntermediate(client,productId){const seen=new Set(),queue=[n(productId)];const hasLineage=Boolean((await client.query("SELECT to_regclass('inventory_product_lineage_rules') item")).rows[0].item);while(queue.length){const current=queue.shift();const recipeRows=(await client.query(`SELECT ri.product_id FROM inventory_recipes r JOIN inventory_recipe_versions rv ON rv.recipe_id=r.id AND rv.status='ACTIVE' JOIN inventory_recipe_ingredients ri ON ri.recipe_version_id=rv.id WHERE r.output_product_id=$1`,[current])).rows;const lineageRows=hasLineage?(await client.query("SELECT parent_product_id product_id FROM inventory_product_lineage_rules WHERE child_product_id=$1 AND active",[current])).rows:[];for(const row of [...recipeRows,...lineageRows]){const id=n(row.product_id);if(!seen.has(id)){seen.add(id);queue.push(id);}}}return seen;}

async function calculateIngredients(client,inputs,outputProductId=null){if(!(inputs||[]).length)fail(400,"Agrega al menos un ingrediente",{ingredients:"Requerido"});const seen=new Set();const lines=[];
  for(const [index,input] of inputs.entries()){const product=(await client.query(`SELECT p.*,u.symbol base_symbol,u.dimension base_dimension FROM inventory_products p JOIN inventory_units u ON u.id=p.base_unit_id WHERE p.id=$1`,[n(input.productId)])).rows[0];if(!product||product.status!=="ACTIVE")fail(400,`Ingrediente ${index+1} no existe o está archivado`);if(seen.has(n(product.id)))fail(400,`El ingrediente ${product.name} está duplicado`);seen.add(n(product.id));if(outputProductId&&n(product.id)===n(outputProductId))fail(400,"Un producto intermedio no puede consumirse a sí mismo");
    const quantity=n(input.quantity),tolerance=n(input.tolerancePercent),waste=n(input.technicalWastePercent);if(quantity<=0)fail(400,`Cantidad no válida para ${product.name}`);if(tolerance<0||tolerance>100||waste<0||waste>100)fail(400,"Tolerancia y merma técnica deben estar entre 0 y 100");const unitId=n(input.unitId);const unit=(await client.query("SELECT id,symbol,dimension FROM inventory_units WHERE id=$1",[unitId])).rows[0];if(!unit)fail(400,"Unidad de ingrediente no válida");const factor=await conversion(client,product,unitId);const baseQuantity=r6(quantity*factor);const unitCost=n(product.average_cost);const lineCost=r6(baseQuantity*(1+waste/100)*unitCost);lines.push({productId:n(product.id),productName:product.name,productType:product.product_type,legacyProductId:product.legacy_id?n(product.legacy_id):null,quantity,unitId,unitSymbol:unit.symbol,baseQuantity,baseUnitSymbol:product.base_symbol,tolerancePercent:tolerance,technicalWastePercent:waste,unitCost,lineCost,consumptionMode:product.product_type==="INTERMEDIATE"?"PREPRODUCED":"MAKE_TO_ORDER"});}
  const directIds=new Set(lines.map(line=>line.productId));for(const line of lines.filter(item=>["INTERMEDIATE","PORTION","PROCESSED"].includes(item.productType))){const descendants=await descendantsOfIntermediate(client,line.productId);if(outputProductId&&descendants.has(n(outputProductId)))fail(400,"La receta formaría un ciclo entre productos preparados");const overlap=[...descendants].find(id=>directIds.has(id));if(overlap){const duplicate=lines.find(item=>item.productId===overlap);fail(400,`Doble consumo: usa ${line.productName} o ${duplicate?.productName||"su materia prima"}, no ambos en el mismo proceso`);}}
  return lines;
}

function metrics(lines,yieldQuantity,salePrice){const totalCost=r6(lines.reduce((sum,line)=>sum+line.lineCost,0));const costPerPortion=r6(totalCost/n(yieldQuantity));const marginAmount=r6(n(salePrice)-costPerPortion);const costPercent=n(salePrice)>0?r6(costPerPortion/n(salePrice)*100):0;const marginPercent=n(salePrice)>0?r6(marginAmount/n(salePrice)*100):0;return{totalCost,costPerPortion,marginAmount,costPercent,marginPercent};}

async function writeIngredients(client,versionId,lines){await client.query("DELETE FROM inventory_recipe_ingredients WHERE recipe_version_id=$1",[versionId]);for(const line of lines)await client.query(`INSERT INTO inventory_recipe_ingredients(recipe_version_id,product_id,quantity,unit_id,consumption_mode,waste_tolerance_percent,technical_waste_percent,base_quantity,unit_cost_snapshot,line_cost) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[versionId,line.productId,line.quantity,line.unitId,line.consumptionMode,line.tolerancePercent,line.technicalWastePercent,line.baseQuantity,line.unitCost,line.lineCost]);}

async function saveDraft(client,recipe,version,payload,actorId){if(version.status!=="DRAFT")fail(409,"Una receta vigente no se edita: crea una versión nueva");const yieldQuantity=n(payload.yieldQuantity??version.yield_quantity);if(yieldQuantity<=0)fail(400,"El rendimiento debe ser mayor a cero");const yieldUnitId=n(payload.yieldUnitId??version.yield_unit_id);if(!yieldUnitId)fail(400,"Selecciona la unidad de rendimiento");const salePrice=n(payload.salePrice??version.sale_price);if(salePrice<0)fail(400,"El precio no puede ser negativo");const inputs=payload.ingredients||await ingredientPayload(client,version.id);const outputProductId=payload.outputProductId===undefined?recipe.output_product_id:(payload.outputProductId?n(payload.outputProductId):null);const lines=await calculateIngredients(client,inputs,outputProductId);const calculated=metrics(lines,yieldQuantity,salePrice);const metadata={technicalRecipe:true,lastCalculatedAt:new Date().toISOString(),...(payload.manual&&typeof payload.manual==="object"?{manual:payload.manual}:{})};await client.query(`UPDATE inventory_recipe_versions SET yield_quantity=$2,yield_unit_id=$3,sale_price=$4,total_cost=$5,cost_per_portion=$6,margin_amount=$7,margin_percent=$8,cost_percent=$9,valid_from=COALESCE($10::timestamptz,valid_from),updated_at=NOW(),metadata=metadata||$11::jsonb WHERE id=$1`,[version.id,yieldQuantity,yieldUnitId,salePrice,calculated.totalCost,calculated.costPerPortion,calculated.marginAmount,calculated.marginPercent,calculated.costPercent,payload.validFrom||null,JSON.stringify(metadata)]);await writeIngredients(client,version.id,lines);if(payload.name||payload.area||payload.outputProductId!==undefined)await client.query("UPDATE inventory_recipes SET name=COALESCE($2,name),area_code=COALESCE($3,area_code),output_product_id=$4,updated_at=NOW() WHERE id=$1",[recipe.id,payload.name||null,payload.area||null,outputProductId]);await audit(client,"SAVE_DRAFT",recipe.id,actorId,`Versión ${version.version} recalculada`,null,{version:version.version,...calculated});}

async function ingredientPayload(client,versionId){return (await client.query(`SELECT product_id "productId",quantity,unit_id "unitId",waste_tolerance_percent "tolerancePercent",technical_waste_percent "technicalWastePercent" FROM inventory_recipe_ingredients WHERE recipe_version_id=$1 ORDER BY id`,[versionId])).rows;}

async function readRecipes(client,recipeId=null){const params=recipeId?[n(recipeId)]:[];const recipes=(await client.query(`SELECT r.id,r.code,r.name,r.area_code "area",r.recipe_type "type",r.output_product_id "outputProductId",op.name "outputProductName",r.legacy_menu_item_id "legacyMenuItemId",r.active,r.created_at "createdAt" FROM inventory_recipes r LEFT JOIN inventory_products op ON op.id=r.output_product_id ${recipeId?"WHERE r.id=$1":""} ORDER BY r.name`,params)).rows;if(!recipes.length)return[];const ids=recipes.map(item=>item.id);const versions=(await client.query(`SELECT rv.id,rv.recipe_id "recipeId",rv.version,rv.status,rv.yield_quantity "yieldQuantity",rv.yield_unit_id "yieldUnitId",u.symbol "yieldUnitSymbol",rv.sale_price "salePrice",rv.total_cost "totalCost",rv.cost_per_portion "costPerPortion",rv.margin_amount "marginAmount",rv.margin_percent "marginPercent",rv.cost_percent "costPercent",rv.valid_from "validFrom",rv.valid_to "validTo",rv.activated_at "activatedAt",rv.archived_at "archivedAt",rv.metadata,rv.created_at "createdAt" FROM inventory_recipe_versions rv LEFT JOIN inventory_units u ON u.id=rv.yield_unit_id WHERE rv.recipe_id=ANY($1::bigint[]) ORDER BY rv.recipe_id,rv.version DESC`,[ids])).rows;const versionIds=versions.map(item=>item.id);const ingredients=versionIds.length?(await client.query(`SELECT ri.id,ri.recipe_version_id "recipeVersionId",ri.product_id "productId",p.name "productName",p.product_type "productType",ri.quantity,ri.unit_id "unitId",u.symbol "unitSymbol",ri.base_quantity "baseQuantity",bu.symbol "baseUnitSymbol",ri.waste_tolerance_percent "tolerancePercent",ri.technical_waste_percent "technicalWastePercent",ri.unit_cost_snapshot "unitCost",ri.line_cost "lineCost",ri.consumption_mode "consumptionMode" FROM inventory_recipe_ingredients ri JOIN inventory_products p ON p.id=ri.product_id JOIN inventory_units u ON u.id=ri.unit_id JOIN inventory_units bu ON bu.id=p.base_unit_id WHERE ri.recipe_version_id=ANY($1::bigint[]) ORDER BY ri.id`,[versionIds])).rows:[];for(const version of versions){version.statusLabel=STATUSES[version.status];version.manual=version.metadata?.manual||{};version.ingredients=ingredients.filter(line=>n(line.recipeVersionId)===n(version.id));}for(const recipe of recipes){recipe.versions=versions.filter(version=>n(version.recipeId)===n(recipe.id));recipe.currentVersion=recipe.versions.find(version=>version.status==="ACTIVE")||recipe.versions[0]||null;}return recipes;}

export async function technicalRecipeReferences(){const [products,units]=await Promise.all([db.query(`SELECT p.id,p.legacy_id "legacyId",p.name,p.product_type "type",p.base_unit_id "baseUnitId",u.symbol "baseUnitSymbol",p.average_cost "cost" FROM inventory_products p JOIN inventory_units u ON u.id=p.base_unit_id WHERE p.status='ACTIVE' ORDER BY p.name`),db.query("SELECT id,code,name,symbol,dimension FROM inventory_units ORDER BY dimension,name")]);const state=(await db.query("SELECT data FROM app_state WHERE id=1")).rows[0].data;return{products:products.rows,units:units.rows,menuItems:(state.menuItems||[]).map(item=>({id:item.id,code:item.code,name:item.name,area:item.area,price:item.price})),areas:[{code:"RESTAURANTE",name:"Cocina / restaurante"},{code:"BARTENDER",name:"Bar"}],statuses:STATUSES,formula:"Costo por porción = Σ(cantidad base × (1 + merma técnica) × costo histórico) ÷ rendimiento"};}
export async function listTechnicalRecipes(){return readRecipes(db);}
export async function getTechnicalRecipe(id){const rows=await readRecipes(db,id);if(!rows.length)fail(404,"Receta no encontrada");return rows[0];}

export async function createTechnicalRecipe(payload,actorId){return tx(async client=>{const type=payload.type==="INTERMEDIATE"?"INTERMEDIATE":"MENU";if(!String(payload.name||"").trim())fail(400,"Ingresa el nombre");if(!String(payload.code||"").trim())fail(400,"Ingresa el código");if(type==="INTERMEDIATE"&&!payload.outputProductId)fail(400,"Una receta intermedia requiere producto de salida");if(type==="INTERMEDIATE"){const output=(await client.query("SELECT product_type FROM inventory_products WHERE id=$1",[n(payload.outputProductId)])).rows[0];if(output?.product_type!=="INTERMEDIATE")fail(400,"El producto de salida debe ser de tipo intermedio");}const recipe=(await client.query(`INSERT INTO inventory_recipes(legacy_menu_item_id,code,name,area_code,recipe_type,output_product_id,active) VALUES($1,$2,$3,$4,$5,$6,TRUE) RETURNING *`,[payload.legacyMenuItemId?n(payload.legacyMenuItemId):null,String(payload.code).trim().toUpperCase(),String(payload.name).trim(),payload.area||"RESTAURANTE",type,payload.outputProductId?n(payload.outputProductId):null])).rows[0];const version=(await client.query(`INSERT INTO inventory_recipe_versions(recipe_id,version,status,yield_quantity,yield_unit_id,sale_price,created_by_legacy_user_id,valid_from,metadata) VALUES($1,1,'DRAFT',$2,$3,$4,$5,COALESCE($6::timestamptz,NOW()),'{"technicalRecipe":true}'::jsonb) RETURNING *`,[recipe.id,n(payload.yieldQuantity)||1,n(payload.yieldUnitId)||null,n(payload.salePrice),actorId,payload.validFrom||null])).rows[0];await saveDraft(client,recipe,version,payload,actorId);await audit(client,"CREATE",recipe.id,actorId,"Receta técnica creada",null,{version:1,status:"DRAFT"});return (await readRecipes(client,recipe.id))[0];});}

export async function updateTechnicalRecipeDraft(recipeId,versionId,payload,actorId){return tx(async client=>{const recipe=await recipeRow(client,recipeId,true);const version=await versionRow(client,versionId,true);if(n(version.recipe_id)!==n(recipe.id))fail(404,"La versión no pertenece a la receta");await saveDraft(client,recipe,version,payload,actorId);return (await readRecipes(client,recipe.id))[0];});}

export async function createTechnicalRecipeVersion(recipeId,payload,actorId){return tx(async client=>{const recipe=await recipeRow(client,recipeId,true);const base=payload.fromVersionId?await versionRow(client,payload.fromVersionId,true):(await client.query("SELECT * FROM inventory_recipe_versions WHERE recipe_id=$1 ORDER BY CASE status WHEN 'ACTIVE' THEN 0 ELSE 1 END,version DESC LIMIT 1",[recipe.id])).rows[0];if(!base)fail(409,"La receta no tiene versión base");const next=n((await client.query("SELECT COALESCE(MAX(version),0)+1 value FROM inventory_recipe_versions WHERE recipe_id=$1",[recipe.id])).rows[0].value);const version=(await client.query(`INSERT INTO inventory_recipe_versions(recipe_id,version,status,yield_quantity,yield_unit_id,sale_price,created_by_legacy_user_id,valid_from,metadata) VALUES($1,$2,'DRAFT',$3,$4,$5,$6,COALESCE($7::timestamptz,NOW()),$8::jsonb) RETURNING *`,[recipe.id,next,n(payload.yieldQuantity??base.yield_quantity),n(payload.yieldUnitId??base.yield_unit_id),n(payload.salePrice??base.sale_price),actorId,payload.validFrom||null,JSON.stringify({technicalRecipe:true,...(base.metadata?.manual?{manual:base.metadata.manual}:{})})])).rows[0];const ingredients=payload.ingredients||await ingredientPayload(client,base.id);await saveDraft(client,recipe,version,{...payload,manual:payload.manual||base.metadata?.manual,ingredients},actorId);await audit(client,"NEW_VERSION",recipe.id,actorId,`Versión ${next} creada desde ${base.version}`,{version:base.version},{version:next,status:"DRAFT"});return (await readRecipes(client,recipe.id))[0];});}

async function syncMenuProjection(client,recipe,version,ingredients){if(!recipe.legacy_menu_item_id)return;const state=(await client.query("SELECT data FROM app_state WHERE id=1 FOR UPDATE")).rows[0].data;const menu=(state.menuItems||[]).find(item=>n(item.id)===n(recipe.legacy_menu_item_id));if(!menu)return;menu.name=recipe.name;menu.area=recipe.area_code;menu.price=n(version.sale_price);menu.recipe=ingredients.map(line=>({inventoryId:line.legacyProductId,quantity:line.baseQuantity})).filter(line=>line.inventoryId);menu.recipeVersionId=n(version.id);menu.recipeVersion=n(version.version);menu.recipeCost=n(version.cost_per_portion);await client.query("UPDATE app_state SET data=$1::jsonb,updated_at=NOW() WHERE id=1",[JSON.stringify(state)]);}

export async function activateTechnicalRecipeVersion(recipeId,versionId,actorId){return tx(async client=>{const recipe=await recipeRow(client,recipeId,true);const version=await versionRow(client,versionId,true);if(n(version.recipe_id)!==n(recipe.id)||version.status!=="DRAFT")fail(409,"Solo una versión borrador puede ponerse vigente");if(new Date(version.valid_from)>new Date())fail(409,"La fecha de vigencia es futura; actívala cuando llegue esa fecha");const inputs=await ingredientPayload(client,version.id);await saveDraft(client,recipe,version,{ingredients:inputs},actorId);const refreshed=await versionRow(client,version.id,true);const ingredients=await calculateIngredients(client,inputs,recipe.output_product_id);await client.query("UPDATE inventory_recipe_versions SET status='ARCHIVED',valid_to=NOW(),archived_at=NOW(),archived_by_legacy_user_id=$2,updated_at=NOW() WHERE recipe_id=$1 AND status='ACTIVE'",[recipe.id,actorId]);await client.query("UPDATE inventory_recipe_versions SET status='ACTIVE',activated_at=NOW(),activated_by_legacy_user_id=$2,valid_from=GREATEST(valid_from,NOW()),updated_at=NOW() WHERE id=$1",[version.id,actorId]);await syncMenuProjection(client,recipe,refreshed,ingredients);await audit(client,"ACTIVATE",recipe.id,actorId,`Versión ${version.version} vigente`,null,{version:version.version,status:"ACTIVE",costPerPortion:n(refreshed.cost_per_portion)});return (await readRecipes(client,recipe.id))[0];});}

export async function archiveTechnicalRecipeVersion(recipeId,versionId,actorId){return tx(async client=>{const recipe=await recipeRow(client,recipeId,true);const version=await versionRow(client,versionId,true);if(n(version.recipe_id)!==n(recipe.id)||version.status==="ARCHIVED")fail(409,"La versión ya está archivada");await client.query("UPDATE inventory_recipe_versions SET status='ARCHIVED',valid_to=NOW(),archived_at=NOW(),archived_by_legacy_user_id=$2,updated_at=NOW() WHERE id=$1",[version.id,actorId]);await audit(client,"ARCHIVE",recipe.id,actorId,`Versión ${version.version} archivada`,{status:version.status},{status:"ARCHIVED"});return (await readRecipes(client,recipe.id))[0];});}

export async function activeRecipeSalesForMenu(menuItemIds){if(!(menuItemIds||[]).length)return{};const rows=(await db.query(`SELECT r.legacy_menu_item_id "menuItemId",rv.id "recipeVersionId",rv.version "recipeVersion",rv.cost_per_portion "recipeUnitCost",rv.sale_price "technicalSalePrice" FROM inventory_recipes r JOIN inventory_recipe_versions rv ON rv.recipe_id=r.id AND rv.status='ACTIVE' AND rv.valid_from<=NOW() AND (rv.valid_to IS NULL OR rv.valid_to>NOW()) WHERE r.legacy_menu_item_id=ANY($1::bigint[]) AND rv.yield_quantity>0 AND rv.yield_unit_id IS NOT NULL AND EXISTS(SELECT 1 FROM inventory_recipe_ingredients ri WHERE ri.recipe_version_id=rv.id) AND NOT EXISTS(SELECT 1 FROM inventory_recipe_ingredients ri WHERE ri.recipe_version_id=rv.id AND ri.base_quantity<=0)`,[[...new Set(menuItemIds.map(n))]])).rows;return Object.fromEntries(rows.map(row=>[n(row.menuItemId),row]));}

export async function recordRecipeSales(orders){if(!(orders||[]).length)return;await tx(async client=>{for(const order of orders){const grouped=new Map();for(const item of order.items||[]){if(!item.recipeVersionId)continue;const current=grouped.get(n(item.menuItemId))||{...item,quantity:0};current.quantity+=n(item.quantity);grouped.set(n(item.menuItemId),current);}for(const item of grouped.values()){const unitCost=n(item.recipeUnitCost),quantity=n(item.quantity),price=n(item.price);await client.query(`INSERT INTO inventory_recipe_sales(legacy_order_id,legacy_order_code,legacy_menu_item_id,recipe_version_id,quantity,recipe_unit_cost,total_recipe_cost,sale_unit_price,total_sale,margin_amount,cost_percent,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ON CONFLICT(legacy_order_id,legacy_menu_item_id) DO NOTHING`,[order.id,order.code,item.menuItemId,item.recipeVersionId,quantity,unitCost,r6(unitCost*quantity),price,r6(price*quantity),r6((price-unitCost)*quantity),price>0?r6(unitCost/price*100):0,JSON.stringify({recipeVersion:item.recipeVersion,groupCode:order.groupCode})]);}}});}

export async function markRecipeSaleStatus(orderId,target){const status=target==="ENTREGADO"?"CONSUMED":target==="CANCELADO"?"CANCELLED":null;if(!status)return;await db.query(`UPDATE inventory_recipe_sales SET status=$2::varchar,consumed_at=CASE WHEN $2::varchar='CONSUMED' THEN NOW() ELSE consumed_at END,cancelled_at=CASE WHEN $2::varchar='CANCELLED' THEN NOW() ELSE cancelled_at END WHERE legacy_order_id=$1 AND status='RESERVED'`,[n(orderId),status]);}

export async function listRecipeSales(recipeId=null){const params=recipeId?[n(recipeId)]:[];return (await db.query(`SELECT s.id,s.legacy_order_id "orderId",s.legacy_order_code "orderCode",s.legacy_menu_item_id "menuItemId",s.recipe_version_id "recipeVersionId",rv.version,s.quantity,s.recipe_unit_cost "recipeUnitCost",s.total_recipe_cost "totalRecipeCost",s.sale_unit_price "saleUnitPrice",s.total_sale "totalSale",s.margin_amount "marginAmount",s.cost_percent "costPercent",s.status,s.created_at "createdAt" FROM inventory_recipe_sales s JOIN inventory_recipe_versions rv ON rv.id=s.recipe_version_id ${recipeId?"WHERE rv.recipe_id=$1":""} ORDER BY s.created_at DESC`,params)).rows;}

export async function operationalRecipeManual(area){
  const normalized=String(area||"").toUpperCase();
  if(!["RESTAURANTE","BARTENDER"].includes(normalized))fail(400,"Área de manual no válida");
  const rows=(await db.query(`
    SELECT r.id,r.code,r.name,r.area_code "area",r.legacy_menu_item_id "menuItemId",
      rv.id "versionId",rv.version,rv.yield_quantity "yieldQuantity",COALESCE(yu.symbol,'porción') "yieldUnitSymbol",
      rv.cost_per_portion "costPerPortion",rv.sale_price "salePrice",rv.metadata,
      ri.product_id "productId",p.name "productName",p.product_type "productType",
      ri.quantity,iu.symbol "unitSymbol",ri.base_quantity "baseQuantity",bu.symbol "baseUnitSymbol",
      ri.technical_waste_percent "technicalWastePercent",ri.waste_tolerance_percent "tolerancePercent",
      ri.consumption_mode "consumptionMode",COALESCE(SUM(CASE WHEN lot.status='AVAILABLE' THEN b.on_hand-b.reserved ELSE 0 END),0) "availableBaseQuantity"
    FROM inventory_recipes r
    JOIN inventory_recipe_versions rv ON rv.recipe_id=r.id AND rv.status='ACTIVE' AND rv.valid_from<=NOW() AND (rv.valid_to IS NULL OR rv.valid_to>NOW())
    JOIN inventory_recipe_ingredients ri ON ri.recipe_version_id=rv.id
    JOIN inventory_products p ON p.id=ri.product_id
    JOIN inventory_units iu ON iu.id=ri.unit_id
    JOIN inventory_units bu ON bu.id=p.base_unit_id
    LEFT JOIN inventory_units yu ON yu.id=rv.yield_unit_id
    JOIN inventory_warehouses w ON w.code=r.area_code AND w.active
    LEFT JOIN inventory_stock_balances b ON b.product_id=p.id AND b.warehouse_id=w.id
    LEFT JOIN inventory_lots lot ON lot.id=b.lot_id
    WHERE r.area_code=$1 AND r.recipe_type='MENU' AND r.active
    GROUP BY r.id,r.code,r.name,r.area_code,r.legacy_menu_item_id,rv.id,rv.version,rv.yield_quantity,yu.symbol,rv.cost_per_portion,rv.sale_price,rv.metadata,ri.id,p.id,iu.id,bu.id
    ORDER BY r.name,ri.id`,[normalized])).rows;
  const byRecipe=new Map();
  for(const row of rows){
    let recipe=byRecipe.get(n(row.id));
    if(!recipe){recipe={id:n(row.id),code:row.code,name:row.name,area:row.area,menuItemId:row.menuItemId?n(row.menuItemId):null,versionId:n(row.versionId),version:n(row.version),yieldQuantity:n(row.yieldQuantity),yieldUnitSymbol:row.yieldUnitSymbol,costPerPortion:n(row.costPerPortion),salePrice:n(row.salePrice),manual:row.metadata?.manual||{},ingredients:[],availablePortions:0,limitingIngredient:null};byRecipe.set(recipe.id,recipe);}
    const required=r6(n(row.baseQuantity)*(1+n(row.technicalWastePercent)/100)/n(row.yieldQuantity));
    const available=n(row.availableBaseQuantity);
    const portions=required>0?Math.floor((available+0.000001)/required):0;
    const ingredient={productId:n(row.productId),productName:row.productName,productType:row.productType,quantity:n(row.quantity),unitSymbol:row.unitSymbol,baseQuantity:n(row.baseQuantity),baseUnitSymbol:row.baseUnitSymbol,requiredPerPortion:required,availableBaseQuantity:available,availablePortions:portions,technicalWastePercent:n(row.technicalWastePercent),tolerancePercent:n(row.tolerancePercent),consumptionMode:row.consumptionMode};
    recipe.ingredients.push(ingredient);
    if(!recipe.limitingIngredient||portions<recipe.limitingIngredient.availablePortions)recipe.limitingIngredient={productId:ingredient.productId,productName:ingredient.productName,availablePortions:portions};
  }
  for(const recipe of byRecipe.values())recipe.availablePortions=recipe.limitingIngredient?.availablePortions||0;
  return [...byRecipe.values()];
}
