DROP TABLE IF EXISTS inventory_migration_runs;
DROP TABLE IF EXISTS inventory_audit_events;
DROP TABLE IF EXISTS inventory_closings;
DROP TABLE IF EXISTS inventory_physical_count_lines;
DROP TABLE IF EXISTS inventory_physical_counts;
DROP TABLE IF EXISTS inventory_shift_sessions;
DROP TABLE IF EXISTS inventory_waste_records;
DROP TABLE IF EXISTS inventory_production_outputs;
DROP TABLE IF EXISTS inventory_production_inputs;
DROP TABLE IF EXISTS inventory_production_batches;
DROP TABLE IF EXISTS inventory_recipe_ingredients;
DROP INDEX IF EXISTS uq_inventory_recipe_active_version;
DROP TABLE IF EXISTS inventory_recipe_versions;
DROP TABLE IF EXISTS inventory_recipes;
DROP TABLE IF EXISTS inventory_transfer_lines;
DROP TABLE IF EXISTS inventory_transfers;
DROP TABLE IF EXISTS inventory_goods_receipt_lines;
DROP TABLE IF EXISTS inventory_goods_receipts;
DROP TABLE IF EXISTS inventory_purchase_order_lines;
DROP TABLE IF EXISTS inventory_purchase_orders;
DROP TABLE IF EXISTS inventory_reservations;
DROP FUNCTION IF EXISTS post_inventory_movement(VARCHAR, VARCHAR, BIGINT, NUMERIC, BIGINT, BIGINT, BIGINT, NUMERIC, VARCHAR, BIGINT, VARCHAR, BIGINT, VARCHAR, BIGINT, BIGINT, BOOLEAN, JSONB);
DROP TRIGGER IF EXISTS trg_inventory_movements_immutable ON inventory_movements;
DROP FUNCTION IF EXISTS reject_inventory_movement_mutation();
DROP TABLE IF EXISTS inventory_movements;
DROP TABLE IF EXISTS inventory_stock_balances;
DROP TABLE IF EXISTS inventory_lots;
DROP TABLE IF EXISTS inventory_suppliers;
DROP TABLE IF EXISTS inventory_warehouses;
DROP TRIGGER IF EXISTS trg_validate_inventory_conversion ON inventory_product_conversions;
DROP FUNCTION IF EXISTS validate_inventory_conversion();
DROP TABLE IF EXISTS inventory_product_conversions;
DROP TABLE IF EXISTS inventory_presentations;
DROP TABLE IF EXISTS inventory_products;
DROP TABLE IF EXISTS inventory_units;
DROP TABLE IF EXISTS inventory_categories;
